#!/usr/bin/env python3
"""Vectrod Font Database — 1500+ SIL OFL"""

GOOGLE_FONTS = [
    {"family":"Roboto","category":"sans-serif","variants":["regular","700"]},
    {"family":"Open Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Noto Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lato","category":"sans-serif","variants":["regular","700"]},
    {"family":"Montserrat","category":"sans-serif","variants":["regular","700"]},
    {"family":"Roboto Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Source Sans 3","category":"sans-serif","variants":["regular","700"]},
    {"family":"Poppins","category":"sans-serif","variants":["regular","700"]},
    {"family":"Roboto Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Oswald","category":"sans-serif","variants":["regular","700"]},
    {"family":"Raleway","category":"sans-serif","variants":["regular","700"]},
    {"family":"Inter","category":"sans-serif","variants":["regular","700"]},
    {"family":"Noto Serif","category":"serif","variants":["regular","700"]},
    {"family":"Ubuntu","category":"sans-serif","variants":["regular","700"]},
    {"family":"Nunito","category":"sans-serif","variants":["regular","700"]},
    {"family":"Playfair Display","category":"serif","variants":["regular","700"]},
    {"family":"Merriweather","category":"serif","variants":["regular","700"]},
    {"family":"Lora","category":"serif","variants":["regular","700"]},
    {"family":"Rubik","category":"sans-serif","variants":["regular","700"]},
    {"family":"Nunito Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mukta","category":"sans-serif","variants":["regular","700"]},
    {"family":"PT Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Work Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kanit","category":"sans-serif","variants":["regular","700"]},
    {"family":"Fira Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Quicksand","category":"sans-serif","variants":["regular","700"]},
    {"family":"Barlow","category":"sans-serif","variants":["regular","700"]},
    {"family":"Josefin Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mulish","category":"sans-serif","variants":["regular","700"]},
    {"family":"DM Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hind Siliguri","category":"sans-serif","variants":["regular","700"]},
    {"family":"Manrope","category":"sans-serif","variants":["regular","700"]},
    {"family":"Titillium Web","category":"sans-serif","variants":["regular","700"]},
    {"family":"Karla","category":"sans-serif","variants":["regular","700"]},
    {"family":"Cabin","category":"sans-serif","variants":["regular","700"]},
    {"family":"Heebo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Ubuntu Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Oxygen","category":"sans-serif","variants":["regular","700"]},
    {"family":"Archivo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Arimo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Dosis","category":"sans-serif","variants":["regular","700"]},
    {"family":"Source Code Pro","category":"monospace","variants":["regular","700"]},
    {"family":"Encode Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Libre Franklin","category":"sans-serif","variants":["regular","700"]},
    {"family":"Exo 2","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lexend","category":"sans-serif","variants":["regular","700"]},
    {"family":"Bebas Neue","category":"display","variants":["regular","700"]},
    {"family":"Anton","category":"display","variants":["regular","700"]},
    {"family":"Lobster","category":"display","variants":["regular","700"]},
    {"family":"Pacifico","category":"display","variants":["regular","700"]},
    {"family":"Abril Fatface","category":"display","variants":["regular","700"]},
    {"family":"Righteous","category":"display","variants":["regular","700"]},
    {"family":"Fredoka One","category":"display","variants":["regular","700"]},
    {"family":"Black Ops One","category":"display","variants":["regular","700"]},
    {"family":"Russo One","category":"display","variants":["regular","700"]},
    {"family":"Bangers","category":"display","variants":["regular","700"]},
    {"family":"Permanent Marker","category":"display","variants":["regular","700"]},
    {"family":"Press Start 2P","category":"display","variants":["regular","700"]},
    {"family":"Titan One","category":"display","variants":["regular","700"]},
    {"family":"Alfa Slab One","category":"display","variants":["regular","700"]},
    {"family":"Boogaloo","category":"display","variants":["regular","700"]},
    {"family":"Lilita One","category":"display","variants":["regular","700"]},
    {"family":"Sigmar One","category":"display","variants":["regular","700"]},
    {"family":"Fugaz One","category":"display","variants":["regular","700"]},
    {"family":"Baloo 2","category":"display","variants":["regular","700"]},
    {"family":"Comfortaa","category":"display","variants":["regular","700"]},
    {"family":"Fredoka","category":"display","variants":["regular","700"]},
    {"family":"Bree Serif","category":"serif","variants":["regular","700"]},
    {"family":"Ultra","category":"serif","variants":["regular","700"]},
    {"family":"Lobster Two","category":"display","variants":["regular","700"]},
    {"family":"Passion One","category":"display","variants":["regular","700"]},
    {"family":"Chewy","category":"display","variants":["regular","700"]},
    {"family":"Bubblegum Sans","category":"display","variants":["regular","700"]},
    {"family":"Rye","category":"display","variants":["regular","700"]},
    {"family":"Creepster","category":"display","variants":["regular","700"]},
    {"family":"Racing Sans One","category":"display","variants":["regular","700"]},
    {"family":"Bungee","category":"display","variants":["regular","700"]},
    {"family":"Bungee Shade","category":"display","variants":["regular","700"]},
    {"family":"Bungee Inline","category":"display","variants":["regular","700"]},
    {"family":"Monoton","category":"display","variants":["regular","700"]},
    {"family":"Audiowide","category":"display","variants":["regular","700"]},
    {"family":"Orbitron","category":"display","variants":["regular","700"]},
    {"family":"Iceland","category":"display","variants":["regular","700"]},
    {"family":"Major Mono Display","category":"monospace","variants":["regular","700"]},
    {"family":"VT323","category":"monospace","variants":["regular","700"]},
    {"family":"Share Tech Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Cutive Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Playfair Display SC","category":"serif","variants":["regular","700"]},
    {"family":"EB Garamond","category":"serif","variants":["regular","700"]},
    {"family":"Cormorant Garamond","category":"serif","variants":["regular","700"]},
    {"family":"Libre Baskerville","category":"serif","variants":["regular","700"]},
    {"family":"Crimson Text","category":"serif","variants":["regular","700"]},
    {"family":"Source Serif 4","category":"serif","variants":["regular","700"]},
    {"family":"PT Serif","category":"serif","variants":["regular","700"]},
    {"family":"Bitter","category":"serif","variants":["regular","700"]},
    {"family":"Rokkitt","category":"serif","variants":["regular","700"]},
    {"family":"Spectral","category":"serif","variants":["regular","700"]},
    {"family":"Zilla Slab","category":"serif","variants":["regular","700"]},
    {"family":"Cardo","category":"serif","variants":["regular","700"]},
    {"family":"Vollkorn","category":"serif","variants":["regular","700"]},
    {"family":"Alegreya","category":"serif","variants":["regular","700"]},
    {"family":"Neuton","category":"serif","variants":["regular","700"]},
    {"family":"Amiri","category":"serif","variants":["regular","700"]},
    {"family":"Josefin Slab","category":"serif","variants":["regular","700"]},
    {"family":"Arvo","category":"serif","variants":["regular","700"]},
    {"family":"Domine","category":"serif","variants":["regular","700"]},
    {"family":"Dancing Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Satisfy","category":"handwriting","variants":["regular","700"]},
    {"family":"Great Vibes","category":"handwriting","variants":["regular","700"]},
    {"family":"Caveat","category":"handwriting","variants":["regular","700"]},
    {"family":"Kalam","category":"handwriting","variants":["regular","700"]},
    {"family":"Sacramento","category":"handwriting","variants":["regular","700"]},
    {"family":"Amatic SC","category":"handwriting","variants":["regular","700"]},
    {"family":"Indie Flower","category":"handwriting","variants":["regular","700"]},
    {"family":"Patrick Hand","category":"handwriting","variants":["regular","700"]},
    {"family":"Rock Salt","category":"handwriting","variants":["regular","700"]},
    {"family":"Courgette","category":"handwriting","variants":["regular","700"]},
    {"family":"Cookie","category":"handwriting","variants":["regular","700"]},
    {"family":"Handlee","category":"handwriting","variants":["regular","700"]},
    {"family":"Gochi Hand","category":"handwriting","variants":["regular","700"]},
    {"family":"Yellowtail","category":"handwriting","variants":["regular","700"]},
    {"family":"Parisienne","category":"handwriting","variants":["regular","700"]},
    {"family":"Allura","category":"handwriting","variants":["regular","700"]},
    {"family":"Alex Brush","category":"handwriting","variants":["regular","700"]},
    {"family":"Tangerine","category":"handwriting","variants":["regular","700"]},
    {"family":"Pinyon Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Rochester","category":"handwriting","variants":["regular","700"]},
    {"family":"Homemade Apple","category":"handwriting","variants":["regular","700"]},
    {"family":"Architects Daughter","category":"handwriting","variants":["regular","700"]},
    {"family":"Coming Soon","category":"handwriting","variants":["regular","700"]},
    {"family":"Shadows Into Light","category":"handwriting","variants":["regular","700"]},
    {"family":"Covered By Your Grace","category":"handwriting","variants":["regular","700"]},
    {"family":"Nothing You Could Do","category":"handwriting","variants":["regular","700"]},
    {"family":"Reenie Beanie","category":"handwriting","variants":["regular","700"]},
    {"family":"La Belle Aurore","category":"handwriting","variants":["regular","700"]},
    {"family":"Zeyada","category":"handwriting","variants":["regular","700"]},
    {"family":"Cedarville Cursive","category":"handwriting","variants":["regular","700"]},
    {"family":"Clicker Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Italianno","category":"handwriting","variants":["regular","700"]},
    {"family":"Marck Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Niconne","category":"handwriting","variants":["regular","700"]},
    {"family":"Norican","category":"handwriting","variants":["regular","700"]},
    {"family":"Waterfall","category":"handwriting","variants":["regular","700"]},
    {"family":"WindSong","category":"handwriting","variants":["regular","700"]},
    {"family":"Whisper","category":"handwriting","variants":["regular","700"]},
    {"family":"DM Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Space Mono","category":"monospace","variants":["regular","700"]},
    {"family":"JetBrains Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Fira Code","category":"monospace","variants":["regular","700"]},
    {"family":"Courier Prime","category":"monospace","variants":["regular","700"]},
    {"family":"Anonymous Pro","category":"monospace","variants":["regular","700"]},
    {"family":"Inconsolata","category":"monospace","variants":["regular","700"]},
    {"family":"Noto Sans Mono","category":"monospace","variants":["regular","700"]},
    {"family":"IBM Plex Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Overpass Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Roboto Slab","category":"serif","variants":["regular","700"]},
    {"family":"Figtree","category":"sans-serif","variants":["regular","700"]},
    {"family":"Outfit","category":"sans-serif","variants":["regular","700"]},
    {"family":"Plus Jakarta Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sora","category":"sans-serif","variants":["regular","700"]},
    {"family":"Albert Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Epilogue","category":"sans-serif","variants":["regular","700"]},
    {"family":"Be Vietnam Pro","category":"sans-serif","variants":["regular","700"]},
    {"family":"Jost","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hanken Grotesk","category":"sans-serif","variants":["regular","700"]},
    {"family":"Space Grotesk","category":"sans-serif","variants":["regular","700"]},
    {"family":"Syne","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lexend Deca","category":"sans-serif","variants":["regular","700"]},
    {"family":"Urbanist","category":"sans-serif","variants":["regular","700"]},
    {"family":"Varela Round","category":"sans-serif","variants":["regular","700"]},
    {"family":"Asap","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hind","category":"sans-serif","variants":["regular","700"]},
    {"family":"Questrial","category":"sans-serif","variants":["regular","700"]},
    {"family":"Nanum Gothic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Overpass","category":"sans-serif","variants":["regular","700"]},
    {"family":"Prompt","category":"sans-serif","variants":["regular","700"]},
    {"family":"Abel","category":"sans-serif","variants":["regular","700"]},
    {"family":"Teko","category":"sans-serif","variants":["regular","700"]},
    {"family":"Barlow Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Barlow Semi Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Catamaran","category":"sans-serif","variants":["regular","700"]},
    {"family":"Fjalla One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Francois One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Fraunces","category":"serif","variants":["regular","700"]},
    {"family":"IBM Plex Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"IBM Plex Serif","category":"serif","variants":["regular","700"]},
    {"family":"Literata","category":"serif","variants":["regular","700"]},
    {"family":"League Gothic","category":"sans-serif","variants":["regular","700"]},
    {"family":"League Spartan","category":"sans-serif","variants":["regular","700"]},
    {"family":"Libre Caslon Text","category":"serif","variants":["regular","700"]},
    {"family":"Livvic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Maven Pro","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mohave","category":"sans-serif","variants":["regular","700"]},
    {"family":"Montagu Slab","category":"serif","variants":["regular","700"]},
    {"family":"Old Standard TT","category":"serif","variants":["regular","700"]},
    {"family":"Piazzolla","category":"serif","variants":["regular","700"]},
    {"family":"Podkova","category":"serif","variants":["regular","700"]},
    {"family":"Poiret One","category":"display","variants":["regular","700"]},
    {"family":"Rajdhani","category":"sans-serif","variants":["regular","700"]},
    {"family":"Ranchers","category":"display","variants":["regular","700"]},
    {"family":"Rowdies","category":"display","variants":["regular","700"]},
    {"family":"Rozha One","category":"serif","variants":["regular","700"]},
    {"family":"Saira","category":"sans-serif","variants":["regular","700"]},
    {"family":"Saira Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sarabun","category":"sans-serif","variants":["regular","700"]},
    {"family":"Secular One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Signika","category":"sans-serif","variants":["regular","700"]},
    {"family":"Staatliches","category":"display","variants":["regular","700"]},
    {"family":"Stardos Stencil","category":"display","variants":["regular","700"]},
    {"family":"Syncopate","category":"sans-serif","variants":["regular","700"]},
    {"family":"Taviraj","category":"serif","variants":["regular","700"]},
    {"family":"Tenor Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Tomorrow","category":"sans-serif","variants":["regular","700"]},
    {"family":"Trade Winds","category":"display","variants":["regular","700"]},
    {"family":"Trirong","category":"serif","variants":["regular","700"]},
    {"family":"Turret Road","category":"display","variants":["regular","700"]},
    {"family":"Viga","category":"sans-serif","variants":["regular","700"]},
    {"family":"Volkhov","category":"serif","variants":["regular","700"]},
    {"family":"Vollkorn SC","category":"serif","variants":["regular","700"]},
    {"family":"Yanone Kaffeesatz","category":"sans-serif","variants":["regular","700"]},
    {"family":"Yantramanav","category":"sans-serif","variants":["regular","700"]},
    {"family":"Yeseva One","category":"display","variants":["regular","700"]},
    {"family":"Yesteryear","category":"handwriting","variants":["regular","700"]},
    {"family":"Yrsa","category":"serif","variants":["regular","700"]},
    {"family":"STIX Two Text","category":"serif","variants":["regular","700"]},
    {"family":"Spectral SC","category":"serif","variants":["regular","700"]},
    {"family":"Special Elite","category":"display","variants":["regular","700"]},
    {"family":"Sofia","category":"handwriting","variants":["regular","700"]},
    {"family":"Sofia Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sonsie One","category":"display","variants":["regular","700"]},
    {"family":"Sorts Mill Goudy","category":"serif","variants":["regular","700"]},
    {"family":"Cinzel","category":"serif","variants":["regular","700"]},
    {"family":"Cinzel Decorative","category":"display","variants":["regular","700"]},
    {"family":"Marcellus","category":"serif","variants":["regular","700"]},
    {"family":"Marcellus SC","category":"serif","variants":["regular","700"]},
    {"family":"Philosopher","category":"serif","variants":["regular","700"]},
    {"family":"Libre Bodoni","category":"serif","variants":["regular","700"]},
    {"family":"Oranienbaum","category":"serif","variants":["regular","700"]},
    {"family":"Rufina","category":"serif","variants":["regular","700"]},
    {"family":"Kreon","category":"serif","variants":["regular","700"]},
    {"family":"Aleo","category":"serif","variants":["regular","700"]},
    {"family":"Poly","category":"serif","variants":["regular","700"]},
    {"family":"Sanchez","category":"serif","variants":["regular","700"]},
    {"family":"Alike","category":"serif","variants":["regular","700"]},
    {"family":"Cambo","category":"serif","variants":["regular","700"]},
    {"family":"Coustard","category":"serif","variants":["regular","700"]},
    {"family":"Pridi","category":"serif","variants":["regular","700"]},
    {"family":"Sahitya","category":"serif","variants":["regular","700"]},
    {"family":"BioRhyme","category":"serif","variants":["regular","700"]},
    {"family":"Inknut Antiqua","category":"serif","variants":["regular","700"]},
    {"family":"Eczar","category":"serif","variants":["regular","700"]},
    {"family":"Vesper Libre","category":"serif","variants":["regular","700"]},
    {"family":"Rasa","category":"serif","variants":["regular","700"]},
    {"family":"Labrada","category":"serif","variants":["regular","700"]},
    {"family":"Rhodium Libre","category":"serif","variants":["regular","700"]},
    {"family":"Gentium Book Plus","category":"serif","variants":["regular","700"]},
    {"family":"Gentium Plus","category":"serif","variants":["regular","700"]},
    {"family":"GFS Neohellenic","category":"serif","variants":["regular","700"]},
    {"family":"Asap Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Encode Sans Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Encode Sans Expanded","category":"sans-serif","variants":["regular","700"]},
    {"family":"Exo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mada","category":"sans-serif","variants":["regular","700"]},
    {"family":"Harmattan","category":"sans-serif","variants":["regular","700"]},
    {"family":"Reem Kufi","category":"sans-serif","variants":["regular","700"]},
    {"family":"Reem Kufi Fun","category":"sans-serif","variants":["regular","700"]},
    {"family":"Changa","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lemonada","category":"sans-serif","variants":["regular","700"]},
    {"family":"Markazi Text","category":"serif","variants":["regular","700"]},
    {"family":"Scheherazade New","category":"serif","variants":["regular","700"]},
    {"family":"Amiri Quran","category":"serif","variants":["regular","700"]},
    {"family":"Katibeh","category":"display","variants":["regular","700"]},
    {"family":"Mirza","category":"serif","variants":["regular","700"]},
    {"family":"Rakkas","category":"display","variants":["regular","700"]},
    {"family":"Lalezar","category":"display","variants":["regular","700"]},
    {"family":"Noto Naskh Arabic","category":"serif","variants":["regular","700"]},
    {"family":"Noto Kufi Arabic","category":"sans-serif","variants":["regular","700"]},
    {"family":"BenchNine","category":"sans-serif","variants":["regular","700"]},
    {"family":"Saira Extra Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Saira Semi Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Cuprum","category":"sans-serif","variants":["regular","700"]},
    {"family":"Krub","category":"sans-serif","variants":["regular","700"]},
    {"family":"Niramit","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mitr","category":"sans-serif","variants":["regular","700"]},
    {"family":"Fahkwang","category":"sans-serif","variants":["regular","700"]},
    {"family":"Pattaya","category":"sans-serif","variants":["regular","700"]},
    {"family":"Charm","category":"handwriting","variants":["regular","700"]},
    {"family":"Charmonman","category":"handwriting","variants":["regular","700"]},
    {"family":"Kodchasan","category":"sans-serif","variants":["regular","700"]},
    {"family":"Maitree","category":"serif","variants":["regular","700"]},
    {"family":"Mali","category":"handwriting","variants":["regular","700"]},
    {"family":"K2D","category":"sans-serif","variants":["regular","700"]},
    {"family":"Bai Jamjuree","category":"sans-serif","variants":["regular","700"]},
    {"family":"Chakra Petch","category":"sans-serif","variants":["regular","700"]},
    {"family":"Chonburi","category":"display","variants":["regular","700"]},
    {"family":"Kantumruy Pro","category":"sans-serif","variants":["regular","700"]},
    {"family":"Srisakdi","category":"handwriting","variants":["regular","700"]},
    {"family":"Thasadith","category":"sans-serif","variants":["regular","700"]},
    {"family":"Athiti","category":"sans-serif","variants":["regular","700"]},
    {"family":"Battambang","category":"display","variants":["regular","700"]},
    {"family":"Bayon","category":"sans-serif","variants":["regular","700"]},
    {"family":"Siemreap","category":"display","variants":["regular","700"]},
    {"family":"DM Serif Display","category":"serif","variants":["regular","700"]},
    {"family":"DM Serif Text","category":"serif","variants":["regular","700"]},
    {"family":"Cormorant","category":"serif","variants":["regular","700"]},
    {"family":"Cormorant Infant","category":"serif","variants":["regular","700"]},
    {"family":"Cormorant SC","category":"serif","variants":["regular","700"]},
    {"family":"Cormorant Unicase","category":"serif","variants":["regular","700"]},
    {"family":"Cormorant Upright","category":"serif","variants":["regular","700"]},
    {"family":"Italiana","category":"serif","variants":["regular","700"]},
    {"family":"Red Hat Display","category":"sans-serif","variants":["regular","700"]},
    {"family":"Red Hat Text","category":"sans-serif","variants":["regular","700"]},
    {"family":"Red Hat Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Recursive","category":"sans-serif","variants":["regular","700"]},
    {"family":"Commissioner","category":"sans-serif","variants":["regular","700"]},
    {"family":"Chivo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Chivo Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Instrument Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Instrument Serif","category":"serif","variants":["regular","700"]},
    {"family":"Familjen Grotesk","category":"sans-serif","variants":["regular","700"]},
    {"family":"Schibsted Grotesk","category":"sans-serif","variants":["regular","700"]},
    {"family":"Onest","category":"sans-serif","variants":["regular","700"]},
    {"family":"Bricolage Grotesque","category":"sans-serif","variants":["regular","700"]},
    {"family":"Noto Sans JP","category":"sans-serif","variants":["regular","700"]},
    {"family":"Noto Sans KR","category":"sans-serif","variants":["regular","700"]},
    {"family":"Noto Sans SC","category":"sans-serif","variants":["regular","700"]},
    {"family":"Noto Sans TC","category":"sans-serif","variants":["regular","700"]},
    {"family":"M PLUS 1p","category":"sans-serif","variants":["regular","700"]},
    {"family":"M PLUS Rounded 1c","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sawarabi Gothic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sawarabi Mincho","category":"serif","variants":["regular","700"]},
    {"family":"Shippori Mincho","category":"serif","variants":["regular","700"]},
    {"family":"Zen Antique","category":"serif","variants":["regular","700"]},
    {"family":"Zen Antique Soft","category":"serif","variants":["regular","700"]},
    {"family":"Klee One","category":"handwriting","variants":["regular","700"]},
    {"family":"Noto Serif JP","category":"serif","variants":["regular","700"]},
    {"family":"Noto Serif KR","category":"serif","variants":["regular","700"]},
    {"family":"Dela Gothic One","category":"display","variants":["regular","700"]},
    {"family":"DotGothic16","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kiwi Maru","category":"serif","variants":["regular","700"]},
    {"family":"Murecho","category":"sans-serif","variants":["regular","700"]},
    {"family":"Rampart One","category":"display","variants":["regular","700"]},
    {"family":"Hina Mincho","category":"serif","variants":["regular","700"]},
    {"family":"Zen Kurenaido","category":"sans-serif","variants":["regular","700"]},
    {"family":"Shippori Antique","category":"sans-serif","variants":["regular","700"]},
    {"family":"Shojumaru","category":"display","variants":["regular","700"]},
    {"family":"Noto Sans Display","category":"sans-serif","variants":["regular","700"]},
    {"family":"Noto Serif Display","category":"serif","variants":["regular","700"]},
    {"family":"Zen Dots","category":"display","variants":["regular","700"]},
    {"family":"Zen Loop","category":"display","variants":["regular","700"]},
    {"family":"Zen Maru Gothic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Zen Old Mincho","category":"serif","variants":["regular","700"]},
    {"family":"Zen Tokyo Zoo","category":"display","variants":["regular","700"]},
    {"family":"Zilla Slab Highlight","category":"display","variants":["regular","700"]},
    {"family":"Wix Madefor Display","category":"sans-serif","variants":["regular","700"]},
    {"family":"Wix Madefor Text","category":"sans-serif","variants":["regular","700"]},
    {"family":"Syne Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Syne Tactile","category":"display","variants":["regular","700"]},
    {"family":"Tapestry","category":"handwriting","variants":["regular","700"]},
    {"family":"Tauri","category":"sans-serif","variants":["regular","700"]},
    {"family":"Tenali Ramakrishna","category":"sans-serif","variants":["regular","700"]},
    {"family":"Text Me One","category":"sans-serif","variants":["regular","700"]},
    {"family":"The Girl Next Door","category":"handwriting","variants":["regular","700"]},
    {"family":"The Nautigal","category":"handwriting","variants":["regular","700"]},
    {"family":"Tienne","category":"serif","variants":["regular","700"]},
    {"family":"Tillana","category":"display","variants":["regular","700"]},
    {"family":"Timmana","category":"sans-serif","variants":["regular","700"]},
    {"family":"Tinos","category":"serif","variants":["regular","700"]},
    {"family":"Trocchi","category":"serif","variants":["regular","700"]},
    {"family":"Trochut","category":"display","variants":["regular","700"]},
    {"family":"Trykker","category":"serif","variants":["regular","700"]},
    {"family":"Tuppence","category":"display","variants":["regular","700"]},
    {"family":"Twinkle Star","category":"handwriting","variants":["regular","700"]},
    {"family":"Unkempt","category":"display","variants":["regular","700"]},
    {"family":"Uroob","category":"sans-serif","variants":["regular","700"]},
    {"family":"Varta","category":"sans-serif","variants":["regular","700"]},
    {"family":"Viaoda Libre","category":"display","variants":["regular","700"]},
    {"family":"Vidaloka","category":"serif","variants":["regular","700"]},
    {"family":"Voces","category":"sans-serif","variants":["regular","700"]},
    {"family":"Warnes","category":"display","variants":["regular","700"]},
    {"family":"Water Brush","category":"handwriting","variants":["regular","700"]},
    {"family":"Wellfleet","category":"display","variants":["regular","700"]},
    {"family":"Wire One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Yomogi","category":"handwriting","variants":["regular","700"]},
    {"family":"Yuji Boku","category":"serif","variants":["regular","700"]},
    {"family":"Yuji Mai","category":"serif","variants":["regular","700"]},
    {"family":"Yuji Syuku","category":"serif","variants":["regular","700"]},
    {"family":"Yusei Magic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Acme","category":"sans-serif","variants":["regular","700"]},
    {"family":"Actor","category":"sans-serif","variants":["regular","700"]},
    {"family":"Adamina","category":"serif","variants":["regular","700"]},
    {"family":"Advent Pro","category":"sans-serif","variants":["regular","700"]},
    {"family":"Aguafina Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Alata","category":"sans-serif","variants":["regular","700"]},
    {"family":"Alatsi","category":"sans-serif","variants":["regular","700"]},
    {"family":"Aldrich","category":"sans-serif","variants":["regular","700"]},
    {"family":"Alegreya Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Alegreya Sans SC","category":"sans-serif","variants":["regular","700"]},
    {"family":"Alegreya SC","category":"serif","variants":["regular","700"]},
    {"family":"Alumni Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Amarante","category":"display","variants":["regular","700"]},
    {"family":"Amaranth","category":"sans-serif","variants":["regular","700"]},
    {"family":"Amethysta","category":"serif","variants":["regular","700"]},
    {"family":"Amiko","category":"sans-serif","variants":["regular","700"]},
    {"family":"Amita","category":"handwriting","variants":["regular","700"]},
    {"family":"Anaheim","category":"sans-serif","variants":["regular","700"]},
    {"family":"Andada Pro","category":"serif","variants":["regular","700"]},
    {"family":"Andika","category":"sans-serif","variants":["regular","700"]},
    {"family":"Anta","category":"sans-serif","variants":["regular","700"]},
    {"family":"Antonio","category":"sans-serif","variants":["regular","700"]},
    {"family":"Anuphan","category":"sans-serif","variants":["regular","700"]},
    {"family":"Anybody","category":"display","variants":["regular","700"]},
    {"family":"Aoboshi One","category":"serif","variants":["regular","700"]},
    {"family":"Arapey","category":"serif","variants":["regular","700"]},
    {"family":"Arbutus","category":"display","variants":["regular","700"]},
    {"family":"Arbutus Slab","category":"serif","variants":["regular","700"]},
    {"family":"Are You Serious","category":"display","variants":["regular","700"]},
    {"family":"Aref Ruqaa","category":"serif","variants":["regular","700"]},
    {"family":"Armata","category":"sans-serif","variants":["regular","700"]},
    {"family":"Arsenal","category":"sans-serif","variants":["regular","700"]},
    {"family":"Artifika","category":"serif","variants":["regular","700"]},
    {"family":"Arya","category":"sans-serif","variants":["regular","700"]},
    {"family":"Asset","category":"display","variants":["regular","700"]},
    {"family":"Assistant","category":"sans-serif","variants":["regular","700"]},
    {"family":"Astloch","category":"display","variants":["regular","700"]},
    {"family":"Asul","category":"sans-serif","variants":["regular","700"]},
    {"family":"Atkinson Hyperlegible","category":"sans-serif","variants":["regular","700"]},
    {"family":"Atma","category":"display","variants":["regular","700"]},
    {"family":"Atomic Age","category":"display","variants":["regular","700"]},
    {"family":"Aubrey","category":"display","variants":["regular","700"]},
    {"family":"Autour One","category":"display","variants":["regular","700"]},
    {"family":"Average","category":"serif","variants":["regular","700"]},
    {"family":"Average Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Averia Gruesa Libre","category":"display","variants":["regular","700"]},
    {"family":"Averia Libre","category":"display","variants":["regular","700"]},
    {"family":"Averia Sans Libre","category":"display","variants":["regular","700"]},
    {"family":"Averia Serif Libre","category":"display","variants":["regular","700"]},
    {"family":"Azeret Mono","category":"monospace","variants":["regular","700"]},
    {"family":"B612","category":"sans-serif","variants":["regular","700"]},
    {"family":"B612 Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Babylonica","category":"handwriting","variants":["regular","700"]},
    {"family":"Bacasime Antique","category":"serif","variants":["regular","700"]},
    {"family":"Bad Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Bagel Fat One","category":"display","variants":["regular","700"]},
    {"family":"Bahiana","category":"display","variants":["regular","700"]},
    {"family":"Bahianita","category":"display","variants":["regular","700"]},
    {"family":"Bakbak One","category":"display","variants":["regular","700"]},
    {"family":"Ballet","category":"display","variants":["regular","700"]},
    {"family":"Baloo Bhai 2","category":"display","variants":["regular","700"]},
    {"family":"Baloo Bhaina 2","category":"display","variants":["regular","700"]},
    {"family":"Baloo Chettan 2","category":"display","variants":["regular","700"]},
    {"family":"Baloo Da 2","category":"display","variants":["regular","700"]},
    {"family":"Baloo Paaji 2","category":"display","variants":["regular","700"]},
    {"family":"Baloo Tamma 2","category":"display","variants":["regular","700"]},
    {"family":"Baloo Tammudu 2","category":"display","variants":["regular","700"]},
    {"family":"Baloo Thambi 2","category":"display","variants":["regular","700"]},
    {"family":"Balsamiq Sans","category":"display","variants":["regular","700"]},
    {"family":"Balthazar","category":"serif","variants":["regular","700"]},
    {"family":"Barriecito","category":"display","variants":["regular","700"]},
    {"family":"Barrio","category":"display","variants":["regular","700"]},
    {"family":"Basic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Baskervville","category":"serif","variants":["regular","700"]},
    {"family":"Baumans","category":"display","variants":["regular","700"]},
    {"family":"Beau Rivage","category":"handwriting","variants":["regular","700"]},
    {"family":"Belgrano","category":"serif","variants":["regular","700"]},
    {"family":"Bellefair","category":"serif","variants":["regular","700"]},
    {"family":"Belleza","category":"sans-serif","variants":["regular","700"]},
    {"family":"Bellota","category":"display","variants":["regular","700"]},
    {"family":"Bellota Text","category":"sans-serif","variants":["regular","700"]},
    {"family":"Benne","category":"serif","variants":["regular","700"]},
    {"family":"Bentham","category":"serif","variants":["regular","700"]},
    {"family":"Berkshire Swash","category":"display","variants":["regular","700"]},
    {"family":"Besley","category":"serif","variants":["regular","700"]},
    {"family":"Beth Ellen","category":"handwriting","variants":["regular","700"]},
    {"family":"Bigelow Rules","category":"display","variants":["regular","700"]},
    {"family":"Bigshot One","category":"display","variants":["regular","700"]},
    {"family":"Bilbo","category":"handwriting","variants":["regular","700"]},
    {"family":"Bilbo Swash Caps","category":"handwriting","variants":["regular","700"]},
    {"family":"Birthstone","category":"handwriting","variants":["regular","700"]},
    {"family":"Birthstone Bounce","category":"handwriting","variants":["regular","700"]},
    {"family":"Biryani","category":"sans-serif","variants":["regular","700"]},
    {"family":"Black And White Picture","category":"serif","variants":["regular","700"]},
    {"family":"Blinker","category":"sans-serif","variants":["regular","700"]},
    {"family":"Bodoni Moda","category":"serif","variants":["regular","700"]},
    {"family":"Bokor","category":"display","variants":["regular","700"]},
    {"family":"Bowlby One","category":"display","variants":["regular","700"]},
    {"family":"Bowlby One SC","category":"display","variants":["regular","700"]},
    {"family":"Brawler","category":"serif","variants":["regular","700"]},
    {"family":"Brygada 1918","category":"serif","variants":["regular","700"]},
    {"family":"Buda","category":"display","variants":["regular","700"]},
    {"family":"Buenard","category":"serif","variants":["regular","700"]},
    {"family":"Bungee Hairline","category":"display","variants":["regular","700"]},
    {"family":"Bungee Outline","category":"display","variants":["regular","700"]},
    {"family":"Bungee Spice","category":"display","variants":["regular","700"]},
    {"family":"Butcherman","category":"display","variants":["regular","700"]},
    {"family":"Butterfly Kids","category":"handwriting","variants":["regular","700"]},
    {"family":"Cabin Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Cabin Sketch","category":"display","variants":["regular","700"]},
    {"family":"Caesar Dressing","category":"display","variants":["regular","700"]},
    {"family":"Cagliostro","category":"sans-serif","variants":["regular","700"]},
    {"family":"Cairo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Cairo Play","category":"display","variants":["regular","700"]},
    {"family":"Caladea","category":"serif","variants":["regular","700"]},
    {"family":"Calistoga","category":"display","variants":["regular","700"]},
    {"family":"Calligraffitti","category":"handwriting","variants":["regular","700"]},
    {"family":"Cambay","category":"sans-serif","variants":["regular","700"]},
    {"family":"Candal","category":"sans-serif","variants":["regular","700"]},
    {"family":"Cantarell","category":"sans-serif","variants":["regular","700"]},
    {"family":"Cantata One","category":"serif","variants":["regular","700"]},
    {"family":"Cantora One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Caprasimo","category":"display","variants":["regular","700"]},
    {"family":"Capriola","category":"sans-serif","variants":["regular","700"]},
    {"family":"Caramel","category":"handwriting","variants":["regular","700"]},
    {"family":"Carattere","category":"handwriting","variants":["regular","700"]},
    {"family":"Carlito","category":"sans-serif","variants":["regular","700"]},
    {"family":"Carme","category":"sans-serif","variants":["regular","700"]},
    {"family":"Carrois Gothic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Carrois Gothic SC","category":"sans-serif","variants":["regular","700"]},
    {"family":"Carter One","category":"display","variants":["regular","700"]},
    {"family":"Castoro","category":"serif","variants":["regular","700"]},
    {"family":"Castoro Titling","category":"display","variants":["regular","700"]},
    {"family":"Caudex","category":"serif","variants":["regular","700"]},
    {"family":"Caveat Brush","category":"handwriting","variants":["regular","700"]},
    {"family":"Ceviche One","category":"display","variants":["regular","700"]},
    {"family":"Changa One","category":"display","variants":["regular","700"]},
    {"family":"Chango","category":"display","variants":["regular","700"]},
    {"family":"Charis SIL","category":"serif","variants":["regular","700"]},
    {"family":"Chathura","category":"sans-serif","variants":["regular","700"]},
    {"family":"Chau Philomene One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Chela One","category":"display","variants":["regular","700"]},
    {"family":"Chelsea Market","category":"display","variants":["regular","700"]},
    {"family":"Chenla","category":"display","variants":["regular","700"]},
    {"family":"Cherish","category":"handwriting","variants":["regular","700"]},
    {"family":"Cherry Bomb One","category":"display","variants":["regular","700"]},
    {"family":"Cherry Cream Soda","category":"display","variants":["regular","700"]},
    {"family":"Cherry Swash","category":"display","variants":["regular","700"]},
    {"family":"Chicle","category":"display","variants":["regular","700"]},
    {"family":"Chilanka","category":"handwriting","variants":["regular","700"]},
    {"family":"Chokokutai","category":"display","variants":["regular","700"]},
    {"family":"Coda","category":"display","variants":["regular","700"]},
    {"family":"Codystar","category":"display","variants":["regular","700"]},
    {"family":"Combo","category":"display","variants":["regular","700"]},
    {"family":"Comforter","category":"handwriting","variants":["regular","700"]},
    {"family":"Comforter Brush","category":"handwriting","variants":["regular","700"]},
    {"family":"Comic Neue","category":"display","variants":["regular","700"]},
    {"family":"Condiment","category":"handwriting","variants":["regular","700"]},
    {"family":"Content","category":"display","variants":["regular","700"]},
    {"family":"Contrail One","category":"display","variants":["regular","700"]},
    {"family":"Convergence","category":"sans-serif","variants":["regular","700"]},
    {"family":"Copse","category":"serif","variants":["regular","700"]},
    {"family":"Corben","category":"display","variants":["regular","700"]},
    {"family":"Corinthia","category":"handwriting","variants":["regular","700"]},
    {"family":"Cousine","category":"monospace","variants":["regular","700"]},
    {"family":"Crafty Girls","category":"handwriting","variants":["regular","700"]},
    {"family":"Crete Round","category":"serif","variants":["regular","700"]},
    {"family":"Crimson Pro","category":"serif","variants":["regular","700"]},
    {"family":"Croissant One","category":"display","variants":["regular","700"]},
    {"family":"Crushed","category":"display","variants":["regular","700"]},
    {"family":"Cute Font","category":"display","variants":["regular","700"]},
    {"family":"Cutive","category":"serif","variants":["regular","700"]},
    {"family":"Damion","category":"handwriting","variants":["regular","700"]},
    {"family":"Dangrek","category":"display","variants":["regular","700"]},
    {"family":"Darker Grotesque","category":"sans-serif","variants":["regular","700"]},
    {"family":"Dawning of a New Day","category":"handwriting","variants":["regular","700"]},
    {"family":"Days One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Dekko","category":"handwriting","variants":["regular","700"]},
    {"family":"Delius","category":"handwriting","variants":["regular","700"]},
    {"family":"Delius Swash Caps","category":"handwriting","variants":["regular","700"]},
    {"family":"Delius Unicase","category":"handwriting","variants":["regular","700"]},
    {"family":"Della Respira","category":"serif","variants":["regular","700"]},
    {"family":"Denk One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Devonshire","category":"handwriting","variants":["regular","700"]},
    {"family":"Dhurjati","category":"sans-serif","variants":["regular","700"]},
    {"family":"Diplomata","category":"display","variants":["regular","700"]},
    {"family":"Diplomata SC","category":"display","variants":["regular","700"]},
    {"family":"Do Hyeon","category":"sans-serif","variants":["regular","700"]},
    {"family":"Dokdo","category":"display","variants":["regular","700"]},
    {"family":"Donegal One","category":"serif","variants":["regular","700"]},
    {"family":"Dongle","category":"sans-serif","variants":["regular","700"]},
    {"family":"Doppio One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Dorsa","category":"sans-serif","variants":["regular","700"]},
    {"family":"Dr Sugiyama","category":"handwriting","variants":["regular","700"]},
    {"family":"Duru Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Dynalight","category":"display","variants":["regular","700"]},
    {"family":"Eagle Lake","category":"display","variants":["regular","700"]},
    {"family":"East Sea Dokdo","category":"handwriting","variants":["regular","700"]},
    {"family":"Eater","category":"display","variants":["regular","700"]},
    {"family":"Economica","category":"sans-serif","variants":["regular","700"]},
    {"family":"Edu NSW ACT Foundation","category":"handwriting","variants":["regular","700"]},
    {"family":"El Messiri","category":"sans-serif","variants":["regular","700"]},
    {"family":"Elsie","category":"display","variants":["regular","700"]},
    {"family":"Elsie Swash Caps","category":"display","variants":["regular","700"]},
    {"family":"Emblema One","category":"display","variants":["regular","700"]},
    {"family":"Emilys Candy","category":"display","variants":["regular","700"]},
    {"family":"Encode Sans SC","category":"sans-serif","variants":["regular","700"]},
    {"family":"Engagement","category":"handwriting","variants":["regular","700"]},
    {"family":"Englebert","category":"sans-serif","variants":["regular","700"]},
    {"family":"Enriqueta","category":"serif","variants":["regular","700"]},
    {"family":"Ephesis","category":"handwriting","variants":["regular","700"]},
    {"family":"Erica One","category":"display","variants":["regular","700"]},
    {"family":"Esteban","category":"serif","variants":["regular","700"]},
    {"family":"Estonia","category":"handwriting","variants":["regular","700"]},
    {"family":"Euphoria Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Ewert","category":"display","variants":["regular","700"]},
    {"family":"Expletus Sans","category":"display","variants":["regular","700"]},
    {"family":"Explora","category":"handwriting","variants":["regular","700"]},
    {"family":"Fanwood Text","category":"serif","variants":["regular","700"]},
    {"family":"Faustina","category":"serif","variants":["regular","700"]},
    {"family":"Federant","category":"display","variants":["regular","700"]},
    {"family":"Federo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Felipa","category":"handwriting","variants":["regular","700"]},
    {"family":"Fenix","category":"serif","variants":["regular","700"]},
    {"family":"Festive","category":"handwriting","variants":["regular","700"]},
    {"family":"Finger Paint","category":"display","variants":["regular","700"]},
    {"family":"Finlandica","category":"sans-serif","variants":["regular","700"]},
    {"family":"Fira Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Fira Sans Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Fira Sans Extra Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Fjord One","category":"serif","variants":["regular","700"]},
    {"family":"Flamenco","category":"display","variants":["regular","700"]},
    {"family":"Flavors","category":"display","variants":["regular","700"]},
    {"family":"Fleur De Leah","category":"handwriting","variants":["regular","700"]},
    {"family":"Fondamento","category":"handwriting","variants":["regular","700"]},
    {"family":"Fontdiner Swanky","category":"display","variants":["regular","700"]},
    {"family":"Forum","category":"display","variants":["regular","700"]},
    {"family":"Fragment Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Frank Ruhl Libre","category":"serif","variants":["regular","700"]},
    {"family":"Freckle Face","category":"display","variants":["regular","700"]},
    {"family":"Fredericka the Great","category":"display","variants":["regular","700"]},
    {"family":"Freehand","category":"display","variants":["regular","700"]},
    {"family":"Fresca","category":"sans-serif","variants":["regular","700"]},
    {"family":"Frijole","category":"display","variants":["regular","700"]},
    {"family":"Fruktur","category":"display","variants":["regular","700"]},
    {"family":"Fuggles","category":"serif","variants":["regular","700"]},
    {"family":"Fuzzy Bubbles","category":"handwriting","variants":["regular","700"]},
    {"family":"GFS Didot","category":"serif","variants":["regular","700"]},
    {"family":"Gabriela","category":"serif","variants":["regular","700"]},
    {"family":"Gaegu","category":"handwriting","variants":["regular","700"]},
    {"family":"Gafata","category":"sans-serif","variants":["regular","700"]},
    {"family":"Galada","category":"display","variants":["regular","700"]},
    {"family":"Galdeano","category":"sans-serif","variants":["regular","700"]},
    {"family":"Galindo","category":"display","variants":["regular","700"]},
    {"family":"Gamja Flower","category":"handwriting","variants":["regular","700"]},
    {"family":"Gantari","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gasoek One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gayathri","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gelasio","category":"serif","variants":["regular","700"]},
    {"family":"Gemunu Libre","category":"sans-serif","variants":["regular","700"]},
    {"family":"Genos","category":"sans-serif","variants":["regular","700"]},
    {"family":"Geo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Geologica","category":"sans-serif","variants":["regular","700"]},
    {"family":"Georama","category":"sans-serif","variants":["regular","700"]},
    {"family":"Geostar","category":"display","variants":["regular","700"]},
    {"family":"Geostar Fill","category":"display","variants":["regular","700"]},
    {"family":"Germania One","category":"display","variants":["regular","700"]},
    {"family":"Gideon Roman","category":"display","variants":["regular","700"]},
    {"family":"Gidugu","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gilda Display","category":"serif","variants":["regular","700"]},
    {"family":"Girassol","category":"display","variants":["regular","700"]},
    {"family":"Give You Glory","category":"handwriting","variants":["regular","700"]},
    {"family":"Glass Antiqua","category":"display","variants":["regular","700"]},
    {"family":"Gloria Hallelujah","category":"handwriting","variants":["regular","700"]},
    {"family":"Gluten","category":"display","variants":["regular","700"]},
    {"family":"Goblin One","category":"display","variants":["regular","700"]},
    {"family":"Goldman","category":"display","variants":["regular","700"]},
    {"family":"Golos Text","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gorditas","category":"display","variants":["regular","700"]},
    {"family":"Gothic A1","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gotu","category":"sans-serif","variants":["regular","700"]},
    {"family":"Goudy Bookletter 1911","category":"serif","variants":["regular","700"]},
    {"family":"Gowun Batang","category":"serif","variants":["regular","700"]},
    {"family":"Gowun Dodum","category":"sans-serif","variants":["regular","700"]},
    {"family":"Graduate","category":"serif","variants":["regular","700"]},
    {"family":"Grand Hotel","category":"handwriting","variants":["regular","700"]},
    {"family":"Grandstander","category":"display","variants":["regular","700"]},
    {"family":"Grape Nuts","category":"handwriting","variants":["regular","700"]},
    {"family":"Gravitas One","category":"display","variants":["regular","700"]},
    {"family":"Grechen Fuemen","category":"handwriting","variants":["regular","700"]},
    {"family":"Grenze","category":"serif","variants":["regular","700"]},
    {"family":"Grenze Gotisch","category":"display","variants":["regular","700"]},
    {"family":"Grey Qo","category":"handwriting","variants":["regular","700"]},
    {"family":"Griffy","category":"display","variants":["regular","700"]},
    {"family":"Gruppo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gudea","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gugi","category":"display","variants":["regular","700"]},
    {"family":"Gulzar","category":"serif","variants":["regular","700"]},
    {"family":"Gupter","category":"serif","variants":["regular","700"]},
    {"family":"Gurajada","category":"sans-serif","variants":["regular","700"]},
    {"family":"Gwendolyn","category":"handwriting","variants":["regular","700"]},
    {"family":"Habibi","category":"serif","variants":["regular","700"]},
    {"family":"Hahmlet","category":"serif","variants":["regular","700"]},
    {"family":"Halant","category":"serif","variants":["regular","700"]},
    {"family":"Hammersmith One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hanalei","category":"display","variants":["regular","700"]},
    {"family":"Hanalei Fill","category":"display","variants":["regular","700"]},
    {"family":"Headland One","category":"serif","variants":["regular","700"]},
    {"family":"Hedvig Letters Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hedvig Letters Serif","category":"serif","variants":["regular","700"]},
    {"family":"Henny Penny","category":"display","variants":["regular","700"]},
    {"family":"Hepta Slab","category":"serif","variants":["regular","700"]},
    {"family":"Herr Von Muellerhoff","category":"handwriting","variants":["regular","700"]},
    {"family":"Hi Melody","category":"handwriting","variants":["regular","700"]},
    {"family":"Hind Guntur","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hind Madurai","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hind Vadodara","category":"sans-serif","variants":["regular","700"]},
    {"family":"Holtwood One SC","category":"serif","variants":["regular","700"]},
    {"family":"Homenaje","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hubballi","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hurricane","category":"handwriting","variants":["regular","700"]},
    {"family":"IM Fell Double Pica","category":"serif","variants":["regular","700"]},
    {"family":"IM Fell English","category":"serif","variants":["regular","700"]},
    {"family":"IM Fell French Canon","category":"serif","variants":["regular","700"]},
    {"family":"IM Fell Great Primer","category":"serif","variants":["regular","700"]},
    {"family":"Ibarra Real Nova","category":"serif","variants":["regular","700"]},
    {"family":"Iceberg","category":"display","variants":["regular","700"]},
    {"family":"Imbue","category":"serif","variants":["regular","700"]},
    {"family":"Imperial Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Imprima","category":"sans-serif","variants":["regular","700"]},
    {"family":"Inclusive Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Inder","category":"sans-serif","variants":["regular","700"]},
    {"family":"Ingrid Darling","category":"handwriting","variants":["regular","700"]},
    {"family":"Inika","category":"serif","variants":["regular","700"]},
    {"family":"Inria Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Inria Serif","category":"serif","variants":["regular","700"]},
    {"family":"Inspiration","category":"handwriting","variants":["regular","700"]},
    {"family":"Inter Tight","category":"sans-serif","variants":["regular","700"]},
    {"family":"Irish Grover","category":"display","variants":["regular","700"]},
    {"family":"Island Moments","category":"handwriting","variants":["regular","700"]},
    {"family":"Istok Web","category":"sans-serif","variants":["regular","700"]},
    {"family":"Itim","category":"handwriting","variants":["regular","700"]},
    {"family":"Jacques Francois","category":"serif","variants":["regular","700"]},
    {"family":"Jacques Francois Shadow","category":"display","variants":["regular","700"]},
    {"family":"Jaldi","category":"sans-serif","variants":["regular","700"]},
    {"family":"Jim Nightshade","category":"display","variants":["regular","700"]},
    {"family":"Joan","category":"serif","variants":["regular","700"]},
    {"family":"Jockey One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Jolly Lodger","category":"display","variants":["regular","700"]},
    {"family":"Jomhuria","category":"display","variants":["regular","700"]},
    {"family":"Jomolhari","category":"serif","variants":["regular","700"]},
    {"family":"Joti One","category":"display","variants":["regular","700"]},
    {"family":"Jua","category":"sans-serif","variants":["regular","700"]},
    {"family":"Judson","category":"serif","variants":["regular","700"]},
    {"family":"Julee","category":"display","variants":["regular","700"]},
    {"family":"Julius Sans One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Junge","category":"serif","variants":["regular","700"]},
    {"family":"Jura","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kablammo","category":"display","variants":["regular","700"]},
    {"family":"Kadwa","category":"serif","variants":["regular","700"]},
    {"family":"Kaushan Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Kavivanar","category":"handwriting","variants":["regular","700"]},
    {"family":"Kavoon","category":"display","variants":["regular","700"]},
    {"family":"Karantina","category":"display","variants":["regular","700"]},
    {"family":"Karma","category":"serif","variants":["regular","700"]},
    {"family":"Keania One","category":"display","variants":["regular","700"]},
    {"family":"Kelly Slab","category":"display","variants":["regular","700"]},
    {"family":"Kenia","category":"display","variants":["regular","700"]},
    {"family":"Kings","category":"handwriting","variants":["regular","700"]},
    {"family":"Kirang Haerang","category":"display","variants":["regular","700"]},
    {"family":"Kite One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Knewave","category":"display","variants":["regular","700"]},
    {"family":"Koh Santepheap","category":"display","variants":["regular","700"]},
    {"family":"Kolker Brush","category":"handwriting","variants":["regular","700"]},
    {"family":"Kosugi","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kosugi Maru","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kotta One","category":"serif","variants":["regular","700"]},
    {"family":"Koulen","category":"display","variants":["regular","700"]},
    {"family":"Kristi","category":"handwriting","variants":["regular","700"]},
    {"family":"Krona One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kufam","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kulim Park","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kumar One","category":"display","variants":["regular","700"]},
    {"family":"Kumar One Outline","category":"display","variants":["regular","700"]},
    {"family":"Kumbh Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kurale","category":"serif","variants":["regular","700"]},
    {"family":"Lacquer","category":"display","variants":["regular","700"]},
    {"family":"Laila","category":"serif","variants":["regular","700"]},
    {"family":"Lakki Reddy","category":"handwriting","variants":["regular","700"]},
    {"family":"Langar","category":"display","variants":["regular","700"]},
    {"family":"Lateef","category":"serif","variants":["regular","700"]},
    {"family":"Lavishly Yours","category":"handwriting","variants":["regular","700"]},
    {"family":"League Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Leckerli One","category":"display","variants":["regular","700"]},
    {"family":"Ledger","category":"serif","variants":["regular","700"]},
    {"family":"Lekton","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lemon","category":"display","variants":["regular","700"]},
    {"family":"Lexend Exa","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lexend Giga","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lexend Mega","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lexend Peta","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lexend Tera","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lexend Zetta","category":"sans-serif","variants":["regular","700"]},
    {"family":"Libre Barcode 128","category":"display","variants":["regular","700"]},
    {"family":"Libre Barcode 39","category":"display","variants":["regular","700"]},
    {"family":"Libre Caslon Display","category":"display","variants":["regular","700"]},
    {"family":"Licorice","category":"handwriting","variants":["regular","700"]},
    {"family":"Life Savers","category":"display","variants":["regular","700"]},
    {"family":"Lily Script One","category":"display","variants":["regular","700"]},
    {"family":"Limelight","category":"display","variants":["regular","700"]},
    {"family":"Linden Hill","category":"serif","variants":["regular","700"]},
    {"family":"Liu Jian Mao Cao","category":"handwriting","variants":["regular","700"]},
    {"family":"Londrina Outline","category":"display","variants":["regular","700"]},
    {"family":"Londrina Shadow","category":"display","variants":["regular","700"]},
    {"family":"Londrina Sketch","category":"display","variants":["regular","700"]},
    {"family":"Londrina Solid","category":"display","variants":["regular","700"]},
    {"family":"Long Cang","category":"handwriting","variants":["regular","700"]},
    {"family":"Love Light","category":"handwriting","variants":["regular","700"]},
    {"family":"Love Ya Like A Sister","category":"display","variants":["regular","700"]},
    {"family":"Loved by the King","category":"handwriting","variants":["regular","700"]},
    {"family":"Lovers Quarrel","category":"handwriting","variants":["regular","700"]},
    {"family":"Luckiest Guy","category":"display","variants":["regular","700"]},
    {"family":"Lugrasimo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lumanosimo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lunasima","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lusitana","category":"serif","variants":["regular","700"]},
    {"family":"Lustria","category":"serif","variants":["regular","700"]},
    {"family":"Luxurious Roman","category":"serif","variants":["regular","700"]},
    {"family":"Luxurious Script","category":"handwriting","variants":["regular","700"]},
    {"family":"M PLUS 1","category":"sans-serif","variants":["regular","700"]},
    {"family":"M PLUS 1 Code","category":"monospace","variants":["regular","700"]},
    {"family":"M PLUS 2","category":"sans-serif","variants":["regular","700"]},
    {"family":"M PLUS Code Latin","category":"monospace","variants":["regular","700"]},
    {"family":"Ma Shan Zheng","category":"handwriting","variants":["regular","700"]},
    {"family":"Macondo","category":"display","variants":["regular","700"]},
    {"family":"Macondo Swash Caps","category":"display","variants":["regular","700"]},
    {"family":"Maiden Orange","category":"display","variants":["regular","700"]},
    {"family":"Mallanna","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mandali","category":"sans-serif","variants":["regular","700"]},
    {"family":"Manjari","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mansalva","category":"display","variants":["regular","700"]},
    {"family":"Manuale","category":"serif","variants":["regular","700"]},
    {"family":"Margarine","category":"display","variants":["regular","700"]},
    {"family":"Marhey","category":"display","variants":["regular","700"]},
    {"family":"Marko One","category":"serif","variants":["regular","700"]},
    {"family":"Marmelad","category":"sans-serif","variants":["regular","700"]},
    {"family":"Martel","category":"serif","variants":["regular","700"]},
    {"family":"Martel Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Martian Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Marvel","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mate","category":"serif","variants":["regular","700"]},
    {"family":"Mate SC","category":"serif","variants":["regular","700"]},
    {"family":"McLaren","category":"display","variants":["regular","700"]},
    {"family":"Mea Culpa","category":"handwriting","variants":["regular","700"]},
    {"family":"Meddon","category":"handwriting","variants":["regular","700"]},
    {"family":"MedievalSharp","category":"display","variants":["regular","700"]},
    {"family":"Medula One","category":"display","variants":["regular","700"]},
    {"family":"Meera Inimai","category":"sans-serif","variants":["regular","700"]},
    {"family":"Meie Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Meow Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Merienda","category":"handwriting","variants":["regular","700"]},
    {"family":"Merriweather Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Metal","category":"display","variants":["regular","700"]},
    {"family":"Metal Mania","category":"display","variants":["regular","700"]},
    {"family":"Metamorphous","category":"display","variants":["regular","700"]},
    {"family":"Metrophobic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Michroma","category":"sans-serif","variants":["regular","700"]},
    {"family":"Milonga","category":"display","variants":["regular","700"]},
    {"family":"Miltonian","category":"display","variants":["regular","700"]},
    {"family":"Miltonian Tattoo","category":"display","variants":["regular","700"]},
    {"family":"Mina","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mingzat","category":"sans-serif","variants":["regular","700"]},
    {"family":"Miniver","category":"display","variants":["regular","700"]},
    {"family":"Miriam Libre","category":"sans-serif","variants":["regular","700"]},
    {"family":"Miss Fajardose","category":"handwriting","variants":["regular","700"]},
    {"family":"Mochiy Pop One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mochiy Pop P One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Modak","category":"display","variants":["regular","700"]},
    {"family":"Modern Antiqua","category":"display","variants":["regular","700"]},
    {"family":"Moirai One","category":"display","variants":["regular","700"]},
    {"family":"Molengo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Molle","category":"handwriting","variants":["regular","700"]},
    {"family":"Monofett","category":"display","variants":["regular","700"]},
    {"family":"Monomaniac One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Monsieur La Doulaise","category":"handwriting","variants":["regular","700"]},
    {"family":"Montez","category":"handwriting","variants":["regular","700"]},
    {"family":"Montserrat Alternates","category":"sans-serif","variants":["regular","700"]},
    {"family":"Montserrat Subrayada","category":"sans-serif","variants":["regular","700"]},
    {"family":"Moo Lah Lah","category":"display","variants":["regular","700"]},
    {"family":"Moon Dance","category":"handwriting","variants":["regular","700"]},
    {"family":"Moul","category":"display","variants":["regular","700"]},
    {"family":"Moulpali","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mountains of Christmas","category":"display","variants":["regular","700"]},
    {"family":"Mouse Memoirs","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mr Bedfort","category":"handwriting","variants":["regular","700"]},
    {"family":"Mr Dafoe","category":"handwriting","variants":["regular","700"]},
    {"family":"Mr De Haviland","category":"handwriting","variants":["regular","700"]},
    {"family":"Mrs Saint Delafield","category":"handwriting","variants":["regular","700"]},
    {"family":"Mrs Sheppards","category":"handwriting","variants":["regular","700"]},
    {"family":"Ms Madi","category":"handwriting","variants":["regular","700"]},
    {"family":"Mukta Mahee","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mukta Malar","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mukta Vaani","category":"sans-serif","variants":["regular","700"]},
    {"family":"MuseoModerno","category":"display","variants":["regular","700"]},
    {"family":"My Soul","category":"handwriting","variants":["regular","700"]},
    {"family":"Mynerve","category":"handwriting","variants":["regular","700"]},
    {"family":"Mystery Quest","category":"display","variants":["regular","700"]},
    {"family":"NTR","category":"sans-serif","variants":["regular","700"]},
    {"family":"Nanum Brush Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Nanum Gothic Coding","category":"monospace","variants":["regular","700"]},
    {"family":"Nanum Pen Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Neonderthaw","category":"handwriting","variants":["regular","700"]},
    {"family":"Nerko One","category":"display","variants":["regular","700"]},
    {"family":"Neucha","category":"handwriting","variants":["regular","700"]},
    {"family":"New Rocker","category":"display","variants":["regular","700"]},
    {"family":"New Tegomin","category":"serif","variants":["regular","700"]},
    {"family":"News Cycle","category":"sans-serif","variants":["regular","700"]},
    {"family":"Nixie One","category":"display","variants":["regular","700"]},
    {"family":"Nokora","category":"serif","variants":["regular","700"]},
    {"family":"Nova Cut","category":"display","variants":["regular","700"]},
    {"family":"Nova Flat","category":"display","variants":["regular","700"]},
    {"family":"Nova Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Nova Oval","category":"display","variants":["regular","700"]},
    {"family":"Nova Round","category":"display","variants":["regular","700"]},
    {"family":"Nova Script","category":"display","variants":["regular","700"]},
    {"family":"Nova Slim","category":"display","variants":["regular","700"]},
    {"family":"Nova Square","category":"display","variants":["regular","700"]},
    {"family":"Numans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Ojuju","category":"sans-serif","variants":["regular","700"]},
    {"family":"Oi","category":"display","variants":["regular","700"]},
    {"family":"Oldenburg","category":"display","variants":["regular","700"]},
    {"family":"Ole","category":"handwriting","variants":["regular","700"]},
    {"family":"Oleo Script","category":"display","variants":["regular","700"]},
    {"family":"Oleo Script Swash Caps","category":"display","variants":["regular","700"]},
    {"family":"Oooh Baby","category":"handwriting","variants":["regular","700"]},
    {"family":"Oregano","category":"display","variants":["regular","700"]},
    {"family":"Original Surfer","category":"display","variants":["regular","700"]},
    {"family":"Over the Rainbow","category":"handwriting","variants":["regular","700"]},
    {"family":"Overlock","category":"display","variants":["regular","700"]},
    {"family":"Overlock SC","category":"display","variants":["regular","700"]},
    {"family":"Ovo","category":"serif","variants":["regular","700"]},
    {"family":"Oxygen Mono","category":"monospace","variants":["regular","700"]},
    {"family":"PT Mono","category":"monospace","variants":["regular","700"]},
    {"family":"PT Sans Caption","category":"sans-serif","variants":["regular","700"]},
    {"family":"PT Sans Narrow","category":"sans-serif","variants":["regular","700"]},
    {"family":"PT Serif Caption","category":"serif","variants":["regular","700"]},
    {"family":"Padauk","category":"sans-serif","variants":["regular","700"]},
    {"family":"Palanquin","category":"sans-serif","variants":["regular","700"]},
    {"family":"Palanquin Dark","category":"sans-serif","variants":["regular","700"]},
    {"family":"Palette Mosaic","category":"display","variants":["regular","700"]},
    {"family":"Pangolin","category":"handwriting","variants":["regular","700"]},
    {"family":"Paprika","category":"display","variants":["regular","700"]},
    {"family":"Passero One","category":"display","variants":["regular","700"]},
    {"family":"Passions Conflict","category":"handwriting","variants":["regular","700"]},
    {"family":"Pathway Extreme","category":"sans-serif","variants":["regular","700"]},
    {"family":"Pathway Gothic One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Patrick Hand SC","category":"handwriting","variants":["regular","700"]},
    {"family":"Peralta","category":"display","variants":["regular","700"]},
    {"family":"Petemoss","category":"handwriting","variants":["regular","700"]},
    {"family":"Petit Formal Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Petrona","category":"serif","variants":["regular","700"]},
    {"family":"Piedra","category":"display","variants":["regular","700"]},
    {"family":"Pirata One","category":"display","variants":["regular","700"]},
    {"family":"Plaster","category":"display","variants":["regular","700"]},
    {"family":"Play","category":"sans-serif","variants":["regular","700"]},
    {"family":"Playpen Sans","category":"handwriting","variants":["regular","700"]},
    {"family":"Poltawski Nowy","category":"serif","variants":["regular","700"]},
    {"family":"Pompiere","category":"display","variants":["regular","700"]},
    {"family":"Poor Story","category":"display","variants":["regular","700"]},
    {"family":"Port Lligat Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Port Lligat Slab","category":"serif","variants":["regular","700"]},
    {"family":"Prairie Wind","category":"display","variants":["regular","700"]},
    {"family":"Praise","category":"handwriting","variants":["regular","700"]},
    {"family":"Prata","category":"serif","variants":["regular","700"]},
    {"family":"Preahvihear","category":"display","variants":["regular","700"]},
    {"family":"Princess Sofia","category":"handwriting","variants":["regular","700"]},
    {"family":"Prosto One","category":"display","variants":["regular","700"]},
    {"family":"Proza Libre","category":"sans-serif","variants":["regular","700"]},
    {"family":"Public Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Puppies Play","category":"handwriting","variants":["regular","700"]},
    {"family":"Puritan","category":"sans-serif","variants":["regular","700"]},
    {"family":"Purple Purse","category":"display","variants":["regular","700"]},
    {"family":"Qahiri","category":"sans-serif","variants":["regular","700"]},
    {"family":"Quando","category":"serif","variants":["regular","700"]},
    {"family":"Quantico","category":"sans-serif","variants":["regular","700"]},
    {"family":"Quattrocento","category":"serif","variants":["regular","700"]},
    {"family":"Quattrocento Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Quintessential","category":"handwriting","variants":["regular","700"]},
    {"family":"Qwigley","category":"handwriting","variants":["regular","700"]},
    {"family":"Qwitcher Grypen","category":"handwriting","variants":["regular","700"]},
    {"family":"Radio Canada","category":"sans-serif","variants":["regular","700"]},
    {"family":"Radley","category":"serif","variants":["regular","700"]},
    {"family":"Raleway Dots","category":"display","variants":["regular","700"]},
    {"family":"Ramabhadra","category":"sans-serif","variants":["regular","700"]},
    {"family":"Ramaraja","category":"serif","variants":["regular","700"]},
    {"family":"Rambla","category":"sans-serif","variants":["regular","700"]},
    {"family":"Readex Pro","category":"sans-serif","variants":["regular","700"]},
    {"family":"Red Rose","category":"display","variants":["regular","700"]},
    {"family":"Reggae One","category":"display","variants":["regular","700"]},
    {"family":"Revalia","category":"display","variants":["regular","700"]},
    {"family":"Ribeye","category":"display","variants":["regular","700"]},
    {"family":"Ribeye Marrow","category":"display","variants":["regular","700"]},
    {"family":"Risque","category":"display","variants":["regular","700"]},
    {"family":"Road Rage","category":"display","variants":["regular","700"]},
    {"family":"Roboto Flex","category":"sans-serif","variants":["regular","700"]},
    {"family":"Romanesco","category":"handwriting","variants":["regular","700"]},
    {"family":"Ropa Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Rosario","category":"sans-serif","variants":["regular","700"]},
    {"family":"Rosarivo","category":"serif","variants":["regular","700"]},
    {"family":"Rouge Script","category":"handwriting","variants":["regular","700"]},
    {"family":"Rubik 80s Fade","category":"display","variants":["regular","700"]},
    {"family":"Rubik Beastly","category":"display","variants":["regular","700"]},
    {"family":"Rubik Bubbles","category":"display","variants":["regular","700"]},
    {"family":"Rubik Burned","category":"display","variants":["regular","700"]},
    {"family":"Rubik Dirt","category":"display","variants":["regular","700"]},
    {"family":"Rubik Distressed","category":"display","variants":["regular","700"]},
    {"family":"Rubik Gemstones","category":"display","variants":["regular","700"]},
    {"family":"Rubik Glitch","category":"display","variants":["regular","700"]},
    {"family":"Rubik Iso","category":"display","variants":["regular","700"]},
    {"family":"Rubik Maze","category":"display","variants":["regular","700"]},
    {"family":"Rubik Microbe","category":"display","variants":["regular","700"]},
    {"family":"Rubik Mono One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Rubik Moonrocks","category":"display","variants":["regular","700"]},
    {"family":"Rubik One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Rubik Pixels","category":"display","variants":["regular","700"]},
    {"family":"Rubik Puddles","category":"display","variants":["regular","700"]},
    {"family":"Rubik Scribble","category":"display","variants":["regular","700"]},
    {"family":"Rubik Spray Paint","category":"display","variants":["regular","700"]},
    {"family":"Rubik Storm","category":"display","variants":["regular","700"]},
    {"family":"Rubik Vinyl","category":"display","variants":["regular","700"]},
    {"family":"Rubik Wet Paint","category":"display","variants":["regular","700"]},
    {"family":"Ruda","category":"sans-serif","variants":["regular","700"]},
    {"family":"Ruge Boogie","category":"display","variants":["regular","700"]},
    {"family":"Ruluko","category":"sans-serif","variants":["regular","700"]},
    {"family":"Rum Raisin","category":"sans-serif","variants":["regular","700"]},
    {"family":"Ruslan Display","category":"display","variants":["regular","700"]},
    {"family":"Ruthie","category":"handwriting","variants":["regular","700"]},
    {"family":"Sail","category":"display","variants":["regular","700"]},
    {"family":"Saira Stencil One","category":"display","variants":["regular","700"]},
    {"family":"Salsa","category":"display","variants":["regular","700"]},
    {"family":"Sancreek","category":"display","variants":["regular","700"]},
    {"family":"Sansita Swashed","category":"display","variants":["regular","700"]},
    {"family":"Scada","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sedan","category":"serif","variants":["regular","700"]},
    {"family":"Sedan SC","category":"serif","variants":["regular","700"]},
    {"family":"Sevillana","category":"display","variants":["regular","700"]},
    {"family":"Seymour One","category":"sans-serif","variants":["regular","700"]},
    {"family":"Shalimar","category":"handwriting","variants":["regular","700"]},
    {"family":"Share","category":"display","variants":["regular","700"]},
    {"family":"Share Tech","category":"sans-serif","variants":["regular","700"]},
    {"family":"Shippori Antique B1","category":"sans-serif","variants":["regular","700"]},
    {"family":"Shippori Mincho B1","category":"serif","variants":["regular","700"]},
    {"family":"Shizuru","category":"display","variants":["regular","700"]},
    {"family":"Sigmar","category":"display","variants":["regular","700"]},
    {"family":"Simonetta","category":"display","variants":["regular","700"]},
    {"family":"Sintony","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sirin Stencil","category":"display","variants":["regular","700"]},
    {"family":"Six Caps","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sixtyfour","category":"display","variants":["regular","700"]},
    {"family":"Skranji","category":"display","variants":["regular","700"]},
    {"family":"Slabo 13px","category":"serif","variants":["regular","700"]},
    {"family":"Slabo 27px","category":"serif","variants":["regular","700"]},
    {"family":"Slackey","category":"display","variants":["regular","700"]},
    {"family":"Slackside One","category":"display","variants":["regular","700"]},
    {"family":"Smokum","category":"display","variants":["regular","700"]},
    {"family":"Smooch","category":"handwriting","variants":["regular","700"]},
    {"family":"Smooch Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Smythe","category":"display","variants":["regular","700"]},
    {"family":"Sofadi One","category":"display","variants":["regular","700"]},
    {"family":"Sofia Sans Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sofia Sans Extra Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sofia Sans Semi Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Solitreo","category":"handwriting","variants":["regular","700"]},
    {"family":"Solway","category":"serif","variants":["regular","700"]},
    {"family":"Song Myung","category":"serif","variants":["regular","700"]},
    {"family":"Spicy Rice","category":"display","variants":["regular","700"]},
    {"family":"Spinnaker","category":"sans-serif","variants":["regular","700"]},
    {"family":"Spirax","category":"display","variants":["regular","700"]},
    {"family":"Splash","category":"handwriting","variants":["regular","700"]},
    {"family":"Spline Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Spline Sans Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Sree Krushnadevaraya","category":"serif","variants":["regular","700"]},
    {"family":"Stoke","category":"serif","variants":["regular","700"]},
    {"family":"Strait","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sue Ellen Francisco","category":"handwriting","variants":["regular","700"]},
    {"family":"Sunshiney","category":"handwriting","variants":["regular","700"]},
    {"family":"Supermercado One","category":"display","variants":["regular","700"]},
    {"family":"Sura","category":"serif","variants":["regular","700"]},
    {"family":"Suranna","category":"serif","variants":["regular","700"]},
    {"family":"Suravaram","category":"serif","variants":["regular","700"]},
    {"family":"Swanky and Moo Moo","category":"handwriting","variants":["regular","700"]},
    {"family":"Tajawal","category":"sans-serif","variants":["regular","700"]},
    {"family":"Taprom","category":"display","variants":["regular","700"]},
    {"family":"Vibes","category":"handwriting","variants":["regular","700"]},
    {"family":"Vibur","category":"handwriting","variants":["regular","700"]},
    {"family":"Yaldevi","category":"sans-serif","variants":["regular","700"]},
    {"family":"Agbalumo","category":"display","variants":["regular","700"]},
    {"family":"Agdasima","category":"sans-serif","variants":["regular","700"]},
    {"family":"Agu Display","category":"display","variants":["regular","700"]},
    {"family":"Akatab","category":"sans-serif","variants":["regular","700"]},
    {"family":"Akaya Kanadaka","category":"display","variants":["regular","700"]},
    {"family":"Akaya Telivigala","category":"display","variants":["regular","700"]},
    {"family":"Akshar","category":"sans-serif","variants":["regular","700"]},
    {"family":"Aladin","category":"display","variants":["regular","700"]},
    {"family":"Alef","category":"sans-serif","variants":["regular","700"]},
    {"family":"Almarai","category":"sans-serif","variants":["regular","700"]},
    {"family":"Arizonia","category":"handwriting","variants":["regular","700"]},
    {"family":"Arima","category":"display","variants":["regular","700"]},
    {"family":"Aref Ruqaa Ink","category":"serif","variants":["regular","700"]},
    {"family":"Spice","category":"display","variants":["regular","700"]},
    {"family":"Allan","category":"display","variants":["regular","700"]},
    {"family":"Allerta","category":"sans-serif","variants":["regular","700"]},
    {"family":"Allerta Stencil","category":"sans-serif","variants":["regular","700"]},
    {"family":"Almendra","category":"serif","variants":["regular","700"]},
    {"family":"Almendra SC","category":"serif","variants":["regular","700"]},
]

FONTSHARE_FONTS = [
    {"family":"Satoshi","category":"sans-serif","source":"fontshare","dl_id":"satoshi"},
    {"family":"Cabinet Grotesk","category":"sans-serif","source":"fontshare","dl_id":"cabinet-grotesk"},
    {"family":"Clash Display","category":"display","source":"fontshare","dl_id":"clash-display"},
    {"family":"Clash Grotesk","category":"sans-serif","source":"fontshare","dl_id":"clash-grotesk"},
    {"family":"General Sans","category":"sans-serif","source":"fontshare","dl_id":"general-sans"},
    {"family":"Switzer","category":"sans-serif","source":"fontshare","dl_id":"switzer"},
    {"family":"Boska","category":"serif","source":"fontshare","dl_id":"boska"},
    {"family":"Chillax","category":"display","source":"fontshare","dl_id":"chillax"},
    {"family":"Supreme","category":"sans-serif","source":"fontshare","dl_id":"supreme"},
    {"family":"Author","category":"sans-serif","source":"fontshare","dl_id":"author"},
    {"family":"Excon","category":"sans-serif","source":"fontshare","dl_id":"excon"},
    {"family":"Synonym","category":"sans-serif","source":"fontshare","dl_id":"synonym"},
    {"family":"Ranade","category":"sans-serif","source":"fontshare","dl_id":"ranade"},
    {"family":"Pencerio","category":"serif","source":"fontshare","dl_id":"pencerio"},
    {"family":"Gambetta","category":"serif","source":"fontshare","dl_id":"gambetta"},
    {"family":"Zodiak","category":"serif","source":"fontshare","dl_id":"zodiak"},
    {"family":"Alpino","category":"sans-serif","source":"fontshare","dl_id":"alpino"},
    {"family":"Tanker","category":"display","source":"fontshare","dl_id":"tanker"},
    {"family":"Pilcrow Rounded","category":"sans-serif","source":"fontshare","dl_id":"pilcrow-rounded"},
    {"family":"Kola","category":"display","source":"fontshare","dl_id":"kola"},
    {"family":"Bespoke Serif","category":"serif","source":"fontshare","dl_id":"bespoke-serif"},
    {"family":"Bespoke Slab","category":"serif","source":"fontshare","dl_id":"bespoke-slab"},
    {"family":"Bespoke Stencil","category":"display","source":"fontshare","dl_id":"bespoke-stencil"},
    {"family":"Nippo","category":"sans-serif","source":"fontshare","dl_id":"nippo"},
    {"family":"Array","category":"monospace","source":"fontshare","dl_id":"array"},
    {"family":"Erode","category":"serif","source":"fontshare","dl_id":"erode"},
    {"family":"Sentient","category":"serif","source":"fontshare","dl_id":"sentient"},
    {"family":"Melodrama","category":"display","source":"fontshare","dl_id":"melodrama"},
    {"family":"Swear Display","category":"display","source":"fontshare","dl_id":"swear-display"},
    {"family":"Nacelle","category":"sans-serif","source":"fontshare","dl_id":"nacelle"},
    {"family":"Archivo Black","category":"sans-serif","source":"fontshare","dl_id":"archivo-black"},
    {"family":"Aspekta","category":"sans-serif","source":"fontshare","dl_id":"aspekta"},
    {"family":"Callie","category":"handwriting","source":"fontshare","dl_id":"callie"},
    {"family":"Geist","category":"sans-serif","source":"fontshare","dl_id":"geist"},
    {"family":"Geist Mono","category":"monospace","source":"fontshare","dl_id":"geist-mono"},
    {"family":"Young Serif","category":"serif","source":"fontshare","dl_id":"young-serif"},
]

LEAGUE_FONTS = [
    {"family":"League Spartan","category":"sans-serif","source":"league"},
    {"family":"League Gothic","category":"sans-serif","source":"league"},
    {"family":"League Mono","category":"monospace","source":"league"},
    {"family":"Chunk Five","category":"serif","source":"league"},
    {"family":"Sniglet","category":"display","source":"league"},
    {"family":"Junction","category":"sans-serif","source":"league"},
    {"family":"Ostrich Sans","category":"sans-serif","source":"league"},
    {"family":"Prociono","category":"serif","source":"league"},
    {"family":"League Script","category":"handwriting","source":"league"},
    {"family":"Raleway","category":"sans-serif","source":"league"},
]

def get_all_fonts():
    r=[]
    for i,f in enumerate(GOOGLE_FONTS): r.append({"family":f["family"],"category":f["category"],"source":"google","variants":["regular","700"],"pop":i})
    for i,f in enumerate(FONTSHARE_FONTS): r.append({"family":f["family"],"category":f["category"],"source":"fontshare","dl_id":f.get("dl_id",""),"pop":i-50})
    for i,f in enumerate(LEAGUE_FONTS): r.append({"family":f["family"],"category":f["category"],"source":"league","pop":i+100})
    return r
if __name__=="__main__":
    print(f"Total: {len(get_all_fonts())}")
