#!/usr/bin/env python3
"""
Vectrod Font Database
Kaynak: Google Fonts (SIL OFL), Fontshare (SIL OFL), League of Moveable Type (SIL OFL)
Tüm fontlar ücretsiz ve telifsiz kullanıma açık.
"""

# Tüm Google Fonts listesi — popularity sıralamasıyla
# Kaynak: fonts.google.com — SIL Open Font License
GOOGLE_FONTS = [
    # TOP 100 MOST POPULAR
    {"family":"Roboto","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Open Sans","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Noto Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Lato","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Montserrat","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Roboto Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Source Sans 3","category":"sans-serif","variants":["regular","700"]},
    {"family":"Poppins","category":"sans-serif","variants":["regular","500","600","700"]},
    {"family":"Roboto Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Oswald","category":"sans-serif","variants":["regular","700"]},
    {"family":"Raleway","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Inter","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Noto Serif","category":"serif","variants":["regular","700"]},
    {"family":"Ubuntu","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Nunito","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Playfair Display","category":"serif","variants":["regular","700","italic"]},
    {"family":"Merriweather","category":"serif","variants":["regular","700","italic"]},
    {"family":"Lora","category":"serif","variants":["regular","700","italic"]},
    {"family":"Rubik","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Nunito Sans","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mukta","category":"sans-serif","variants":["regular","700"]},
    {"family":"PT Sans","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Work Sans","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Noto Sans JP","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kanit","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Lato","category":"sans-serif","variants":["300","regular","700","900"]},
    {"family":"Fira Sans","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Quicksand","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Barlow","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Josefin Sans","category":"sans-serif","variants":["regular","600","700"]},
    {"family":"Mulish","category":"sans-serif","variants":["regular","700"]},
    {"family":"Noto Sans KR","category":"sans-serif","variants":["regular","700"]},
    {"family":"DM Sans","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Hind Siliguri","category":"sans-serif","variants":["regular","700"]},
    {"family":"Manrope","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Titillium Web","category":"sans-serif","variants":["regular","600","700"]},
    {"family":"Karla","category":"sans-serif","variants":["regular","700"]},
    {"family":"Cabin","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Noto Sans SC","category":"sans-serif","variants":["regular","700"]},
    {"family":"Heebo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Ubuntu Condensed","category":"sans-serif","variants":["regular"]},
    {"family":"Oxygen","category":"sans-serif","variants":["300","regular","700"]},
    {"family":"Archivo","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Arimo","category":"sans-serif","variants":["regular","700"]},
    {"family":"Dosis","category":"sans-serif","variants":["regular","600","700"]},
    {"family":"Source Code Pro","category":"monospace","variants":["regular","500","700"]},
    {"family":"Encode Sans","category":"sans-serif","variants":["regular","600","700"]},
    {"family":"Libre Franklin","category":"sans-serif","variants":["regular","600","700"]},
    {"family":"Exo 2","category":"sans-serif","variants":["regular","600","700"]},
    {"family":"Lexend","category":"sans-serif","variants":["regular","500","700"]},
    # DISPLAY & DECORATIVE
    {"family":"Bebas Neue","category":"display","variants":["regular"]},
    {"family":"Anton","category":"display","variants":["regular"]},
    {"family":"Lobster","category":"display","variants":["regular"]},
    {"family":"Pacifico","category":"display","variants":["regular"]},
    {"family":"Abril Fatface","category":"display","variants":["regular"]},
    {"family":"Righteous","category":"display","variants":["regular"]},
    {"family":"Fredoka One","category":"display","variants":["regular"]},
    {"family":"Black Ops One","category":"display","variants":["regular"]},
    {"family":"Russo One","category":"display","variants":["regular"]},
    {"family":"Bangers","category":"display","variants":["regular"]},
    {"family":"Permanent Marker","category":"display","variants":["regular"]},
    {"family":"Press Start 2P","category":"display","variants":["regular"]},
    {"family":"Titan One","category":"display","variants":["regular"]},
    {"family":"Alfa Slab One","category":"display","variants":["regular"]},
    {"family":"Boogaloo","category":"display","variants":["regular"]},
    {"family":"Coiny","category":"display","variants":["regular"]},
    {"family":"Lilita One","category":"display","variants":["regular"]},
    {"family":"Sigmar One","category":"display","variants":["regular"]},
    {"family":"Fugaz One","category":"display","variants":["regular"]},
    {"family":"Baloo 2","category":"display","variants":["regular","500","700"]},
    {"family":"Comfortaa","category":"display","variants":["regular","500","700"]},
    {"family":"Fredoka","category":"display","variants":["regular","500","700"]},
    {"family":"Bree Serif","category":"serif","variants":["regular"]},
    {"family":"Ultra","category":"serif","variants":["regular"]},
    {"family":"Lobster Two","category":"display","variants":["regular","italic"]},
    {"family":"Exo","category":"sans-serif","variants":["regular","600","700"]},
    {"family":"Passion One","category":"display","variants":["regular","700"]},
    {"family":"Monda","category":"sans-serif","variants":["regular","700"]},
    {"family":"Rammetto One","category":"display","variants":["regular"]},
    {"family":"Leckerli One","category":"display","variants":["regular"]},
    {"family":"Boogaloo","category":"display","variants":["regular"]},
    {"family":"Calistoga","category":"display","variants":["regular"]},
    {"family":"Chewy","category":"display","variants":["regular"]},
    {"family":"Bubblegum Sans","category":"display","variants":["regular"]},
    {"family":"Sancreek","category":"display","variants":["regular"]},
    {"family":"Rye","category":"display","variants":["regular"]},
    {"family":"Creepster","category":"display","variants":["regular"]},
    {"family":"Faster One","category":"display","variants":["regular"]},
    {"family":"Racing Sans One","category":"display","variants":["regular"]},
    {"family":"Bungee","category":"display","variants":["regular"]},
    {"family":"Bungee Shade","category":"display","variants":["regular"]},
    {"family":"Bungee Inline","category":"display","variants":["regular"]},
    {"family":"Monoton","category":"display","variants":["regular"]},
    {"family":"Audiowide","category":"display","variants":["regular"]},
    {"family":"Orbitron","category":"display","variants":["regular","500","700"]},
    {"family":"Iceland","category":"display","variants":["regular"]},
    {"family":"Major Mono Display","category":"monospace","variants":["regular"]},
    {"family":"VT323","category":"monospace","variants":["regular"]},
    {"family":"Share Tech Mono","category":"monospace","variants":["regular"]},
    {"family":"Cutive Mono","category":"monospace","variants":["regular"]},
    # SERIF
    {"family":"Playfair Display SC","category":"serif","variants":["regular","700"]},
    {"family":"EB Garamond","category":"serif","variants":["regular","500","700"]},
    {"family":"Cormorant Garamond","category":"serif","variants":["300","regular","500","600","700"]},
    {"family":"Libre Baskerville","category":"serif","variants":["regular","700","italic"]},
    {"family":"Crimson Text","category":"serif","variants":["regular","600","italic"]},
    {"family":"Source Serif 4","category":"serif","variants":["regular","600","700"]},
    {"family":"PT Serif","category":"serif","variants":["regular","700","italic"]},
    {"family":"Bitter","category":"serif","variants":["regular","500","700"]},
    {"family":"Rokkitt","category":"serif","variants":["regular","500","700"]},
    {"family":"Spectral","category":"serif","variants":["regular","500","700"]},
    {"family":"Zilla Slab","category":"serif","variants":["regular","500","700"]},
    {"family":"Cardo","category":"serif","variants":["regular","700","italic"]},
    {"family":"Vollkorn","category":"serif","variants":["regular","500","700"]},
    {"family":"Alegreya","category":"serif","variants":["regular","500","700"]},
    {"family":"Neuton","category":"serif","variants":["regular","700","italic"]},
    {"family":"Unna","category":"serif","variants":["regular","700","italic"]},
    {"family":"Amiri","category":"serif","variants":["regular","700","italic"]},
    {"family":"Charis SIL","category":"serif","variants":["regular","700"]},
    {"family":"Libre Caslon Text","category":"serif","variants":["regular","700","italic"]},
    {"family":"Gelasio","category":"serif","variants":["regular","500","700"]},
    {"family":"GFS Didot","category":"serif","variants":["regular"]},
    {"family":"Josefin Slab","category":"serif","variants":["regular","700","italic"]},
    {"family":"Aleo","category":"serif","variants":["regular","700"]},
    {"family":"Podkova","category":"serif","variants":["regular","500","700"]},
    {"family":"Arvo","category":"serif","variants":["regular","700","italic"]},
    {"family":"Domine","category":"serif","variants":["regular","500","700"]},
    {"family":"Noto Serif Display","category":"serif","variants":["regular","700","italic"]},
    # HANDWRITING & SCRIPT
    {"family":"Dancing Script","category":"handwriting","variants":["regular","500","700"]},
    {"family":"Satisfy","category":"handwriting","variants":["regular"]},
    {"family":"Great Vibes","category":"handwriting","variants":["regular"]},
    {"family":"Caveat","category":"handwriting","variants":["regular","500","700"]},
    {"family":"Kalam","category":"handwriting","variants":["300","regular","700"]},
    {"family":"Sacramento","category":"handwriting","variants":["regular"]},
    {"family":"Amatic SC","category":"handwriting","variants":["regular","700"]},
    {"family":"Indie Flower","category":"handwriting","variants":["regular"]},
    {"family":"Patrick Hand","category":"handwriting","variants":["regular"]},
    {"family":"Rock Salt","category":"handwriting","variants":["regular"]},
    {"family":"Courgette","category":"handwriting","variants":["regular"]},
    {"family":"Cookie","category":"handwriting","variants":["regular"]},
    {"family":"Handlee","category":"handwriting","variants":["regular"]},
    {"family":"Gochi Hand","category":"handwriting","variants":["regular"]},
    {"family":"Yellowtail","category":"handwriting","variants":["regular"]},
    {"family":"Parisienne","category":"handwriting","variants":["regular"]},
    {"family":"Allura","category":"handwriting","variants":["regular"]},
    {"family":"Alex Brush","category":"handwriting","variants":["regular"]},
    {"family":"Tangerine","category":"handwriting","variants":["regular","700"]},
    {"family":"Pinyon Script","category":"handwriting","variants":["regular"]},
    {"family":"Rochester","category":"handwriting","variants":["regular"]},
    {"family":"Homemade Apple","category":"handwriting","variants":["regular"]},
    {"family":"Architects Daughter","category":"handwriting","variants":["regular"]},
    {"family":"Coming Soon","category":"handwriting","variants":["regular"]},
    {"family":"Just Another Hand","category":"handwriting","variants":["regular"]},
    {"family":"Shadows Into Light","category":"handwriting","variants":["regular"]},
    {"family":"Shadows Into Light Two","category":"handwriting","variants":["regular"]},
    {"family":"Covered By Your Grace","category":"handwriting","variants":["regular"]},
    {"family":"Nothing You Could Do","category":"handwriting","variants":["regular"]},
    {"family":"Reenie Beanie","category":"handwriting","variants":["regular"]},
    {"family":"Permanent Marker","category":"handwriting","variants":["regular"]},
    {"family":"Sue Ellen Francisco","category":"handwriting","variants":["regular"]},
    {"family":"La Belle Aurore","category":"handwriting","variants":["regular"]},
    {"family":"Zeyada","category":"handwriting","variants":["regular"]},
    {"family":"Cedarville Cursive","category":"handwriting","variants":["regular"]},
    {"family":"Clicker Script","category":"handwriting","variants":["regular"]},
    {"family":"Qwigley","category":"handwriting","variants":["regular"]},
    {"family":"Herr Von Muellerhoff","category":"handwriting","variants":["regular"]},
    {"family":"Italianno","category":"handwriting","variants":["regular"]},
    {"family":"Marck Script","category":"handwriting","variants":["regular"]},
    {"family":"Meddon","category":"handwriting","variants":["regular"]},
    {"family":"Meie Script","category":"handwriting","variants":["regular"]},
    {"family":"Miss Fajardose","category":"handwriting","variants":["regular"]},
    {"family":"Molle","category":"handwriting","variants":["italic"]},
    {"family":"Monsieur La Doulaise","category":"handwriting","variants":["regular"]},
    {"family":"Mrs Saint Delafield","category":"handwriting","variants":["regular"]},
    {"family":"Mrs Sheppards","category":"handwriting","variants":["regular"]},
    {"family":"Niconne","category":"handwriting","variants":["italic"]},
    {"family":"Norican","category":"handwriting","variants":["regular"]},
    {"family":"Ruthie","category":"handwriting","variants":["regular"]},
    {"family":"Srisakdi","category":"handwriting","variants":["regular","700"]},
    {"family":"Stalemate","category":"handwriting","variants":["regular"]},
    {"family":"Sunshiney","category":"handwriting","variants":["regular"]},
    {"family":"Swanky and Moo Moo","category":"handwriting","variants":["regular"]},
    {"family":"Vibes","category":"handwriting","variants":["regular"]},
    {"family":"Waterfall","category":"handwriting","variants":["regular"]},
    {"family":"Whisper","category":"handwriting","variants":["regular"]},
    {"family":"WindSong","category":"handwriting","variants":["regular"]},
    # MONOSPACE
    {"family":"DM Mono","category":"monospace","variants":["regular","500","italic"]},
    {"family":"Space Mono","category":"monospace","variants":["regular","700","italic"]},
    {"family":"JetBrains Mono","category":"monospace","variants":["regular","500","700"]},
    {"family":"Fira Code","category":"monospace","variants":["regular","500","700"]},
    {"family":"Courier Prime","category":"monospace","variants":["regular","700","italic"]},
    {"family":"Anonymous Pro","category":"monospace","variants":["regular","700","italic"]},
    {"family":"Inconsolata","category":"monospace","variants":["regular","700"]},
    {"family":"Noto Sans Mono","category":"monospace","variants":["regular","700"]},
    {"family":"B612 Mono","category":"monospace","variants":["regular","700","italic"]},
    {"family":"IBM Plex Mono","category":"monospace","variants":["regular","500","700"]},
    {"family":"Overpass Mono","category":"monospace","variants":["regular","700"]},
    {"family":"Roboto Slab","category":"serif","variants":["regular","500","700"]},
    # MORE SANS-SERIF
    {"family":"Figtree","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Outfit","category":"sans-serif","variants":["regular","400","500","700"]},
    {"family":"Plus Jakarta Sans","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Sora","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Albert Sans","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Epilogue","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Be Vietnam Pro","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Noto Sans Display","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Jost","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Hanken Grotesk","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Schibsted Grotesk","category":"sans-serif","variants":["regular","700"]},
    {"family":"Red Hat Display","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Red Hat Text","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Onest","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Geist","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Bricolage Grotesque","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Space Grotesk","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Syne","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Lexend Deca","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Urbanist","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Nunito","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Varela Round","category":"sans-serif","variants":["regular"]},
    {"family":"Asap","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Muli","category":"sans-serif","variants":["regular","700"]},
    {"family":"Hind","category":"sans-serif","variants":["300","regular","500","700"]},
    {"family":"Questrial","category":"sans-serif","variants":["regular"]},
    {"family":"Nanum Gothic","category":"sans-serif","variants":["regular","700"]},
    {"family":"Overpass","category":"sans-serif","variants":["regular","700"]},
    {"family":"Prompt","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Kreon","category":"serif","variants":["regular","500","700"]},
    {"family":"Abel","category":"sans-serif","variants":["regular"]},
    {"family":"Teko","category":"sans-serif","variants":["300","regular","500","700"]},
    {"family":"Asap Condensed","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Barlow Condensed","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Barlow Semi Condensed","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"BioRhyme","category":"serif","variants":["300","regular","700"]},
    {"family":"Cambo","category":"serif","variants":["regular"]},
    {"family":"Catamaran","category":"sans-serif","variants":["regular","700"]},
    {"family":"Changa","category":"sans-serif","variants":["regular","700"]},
    {"family":"Crete Round","category":"serif","variants":["regular","italic"]},
    {"family":"Cuprum","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Didact Gothic","category":"sans-serif","variants":["regular"]},
    {"family":"Electrolize","category":"sans-serif","variants":["regular"]},
    {"family":"Encode Sans Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Encode Sans Expanded","category":"sans-serif","variants":["regular","700"]},
    {"family":"Fahkwang","category":"sans-serif","variants":["regular","700"]},
    {"family":"Farro","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Fjalla One","category":"sans-serif","variants":["regular"]},
    {"family":"Francois One","category":"sans-serif","variants":["regular"]},
    {"family":"Fraunces","category":"serif","variants":["regular","500","700"]},
    {"family":"Gothic A1","category":"sans-serif","variants":["regular","700"]},
    {"family":"Graduate","category":"serif","variants":["regular"]},
    {"family":"Hammersmith One","category":"sans-serif","variants":["regular"]},
    {"family":"Harmattan","category":"sans-serif","variants":["regular","700"]},
    {"family":"IBM Plex Sans","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"IBM Plex Serif","category":"serif","variants":["regular","500","700"]},
    {"family":"Istok Web","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Jaldi","category":"sans-serif","variants":["regular","700"]},
    {"family":"Kantumruy Pro","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Khand","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Khula","category":"sans-serif","variants":["regular","700"]},
    {"family":"Krub","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Labrada","category":"serif","variants":["regular","700"]},
    {"family":"Lato","category":"sans-serif","variants":["regular","700"]},
    {"family":"Literata","category":"serif","variants":["regular","500","700"]},
    {"family":"Lancelot","category":"display","variants":["regular"]},
    {"family":"League Gothic","category":"sans-serif","variants":["regular"]},
    {"family":"League Spartan","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Libre Barcode 128","category":"display","variants":["regular"]},
    {"family":"Livvic","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"M PLUS 1p","category":"sans-serif","variants":["regular","700"]},
    {"family":"M PLUS Rounded 1c","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mada","category":"sans-serif","variants":["regular","700"]},
    {"family":"Magra","category":"sans-serif","variants":["regular","700"]},
    {"family":"Mali","category":"handwriting","variants":["regular","500","700"]},
    {"family":"Markazi Text","category":"serif","variants":["regular","500","700"]},
    {"family":"Maven Pro","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Mitr","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Mohave","category":"sans-serif","variants":["regular","700"]},
    {"family":"Montagu Slab","category":"serif","variants":["regular","500","700"]},
    {"family":"Mukta Malar","category":"sans-serif","variants":["regular","700"]},
    {"family":"Narnoor","category":"serif","variants":["regular","700"]},
    {"family":"Neucha","category":"handwriting","variants":["regular"]},
    {"family":"Neuton","category":"serif","variants":["regular","700","italic"]},
    {"family":"Niramit","category":"sans-serif","variants":["regular","700"]},
    {"family":"Nobile","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Noticia Text","category":"serif","variants":["regular","700","italic"]},
    {"family":"Noto Serif JP","category":"serif","variants":["regular","700"]},
    {"family":"Nunito","category":"sans-serif","variants":["regular","700"]},
    {"family":"Odibee Sans","category":"display","variants":["regular"]},
    {"family":"Offside","category":"display","variants":["regular"]},
    {"family":"Old Standard TT","category":"serif","variants":["regular","700","italic"]},
    {"family":"Oooh Baby","category":"handwriting","variants":["regular"]},
    {"family":"Oranienbaum","category":"serif","variants":["regular"]},
    {"family":"Orelega One","category":"display","variants":["regular"]},
    {"family":"Orienta","category":"sans-serif","variants":["regular"]},
    {"family":"Overlock","category":"display","variants":["regular","700","italic"]},
    {"family":"Oxanium","category":"display","variants":["regular","500","700"]},
    {"family":"Pattaya","category":"sans-serif","variants":["regular"]},
    {"family":"Patua One","category":"display","variants":["regular"]},
    {"family":"Paytone One","category":"sans-serif","variants":["regular"]},
    {"family":"Phudu","category":"display","variants":["regular","500","700"]},
    {"family":"Piazzolla","category":"serif","variants":["regular","500","700","italic"]},
    {"family":"Playball","category":"display","variants":["regular"]},
    {"family":"Platypi","category":"serif","variants":["regular","500","700"]},
    {"family":"Plyfair Display","category":"serif","variants":["regular","700","italic"]},
    {"family":"Podkova","category":"serif","variants":["regular","500","700"]},
    {"family":"Poiret One","category":"display","variants":["regular"]},
    {"family":"Poly","category":"serif","variants":["regular","italic"]},
    {"family":"Pontano Sans","category":"sans-serif","variants":["regular"]},
    {"family":"Poor Story","category":"display","variants":["regular"]},
    {"family":"Potta One","category":"display","variants":["regular"]},
    {"family":"Pragati Narrow","category":"sans-serif","variants":["regular","700"]},
    {"family":"Pridi","category":"serif","variants":["regular","500","700"]},
    {"family":"Princess Sofia","category":"handwriting","variants":["regular"]},
    {"family":"Prociono","category":"serif","variants":["regular"]},
    {"family":"Rajdhani","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Rakkas","category":"display","variants":["regular"]},
    {"family":"Ranchers","category":"display","variants":["regular"]},
    {"family":"Rancho","category":"handwriting","variants":["regular"]},
    {"family":"Ranga","category":"display","variants":["regular","700"]},
    {"family":"Rasa","category":"serif","variants":["regular","500","700"]},
    {"family":"Reem Kufi","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Reem Kufi Fun","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Reem Kufi Ink","category":"sans-serif","variants":["regular"]},
    {"family":"Revalia","category":"display","variants":["regular"]},
    {"family":"Rhodium Libre","category":"serif","variants":["regular"]},
    {"family":"Ribeye","category":"display","variants":["regular"]},
    {"family":"Ribeye Marrow","category":"display","variants":["regular"]},
    {"family":"Righteous","category":"display","variants":["regular"]},
    {"family":"Risque","category":"display","variants":["regular"]},
    {"family":"Road Rage","category":"display","variants":["regular"]},
    {"family":"Roboto Serif","category":"serif","variants":["regular","500","700"]},
    {"family":"Roboto Flex","category":"sans-serif","variants":["regular"]},
    {"family":"Rouge Script","category":"handwriting","variants":["regular"]},
    {"family":"Rowdies","category":"display","variants":["300","regular","700"]},
    {"family":"Rozha One","category":"serif","variants":["regular"]},
    {"family":"Ruda","category":"sans-serif","variants":["regular","700"]},
    {"family":"Rufina","category":"serif","variants":["regular","700"]},
    {"family":"Ruge Boogie","category":"display","variants":["regular"]},
    {"family":"Ruluko","category":"sans-serif","variants":["regular"]},
    {"family":"Rum Raisin","category":"sans-serif","variants":["regular"]},
    {"family":"Ruslan Display","category":"display","variants":["regular"]},
    {"family":"Russo One","category":"sans-serif","variants":["regular"]},
    {"family":"Ruthie","category":"handwriting","variants":["regular"]},
    {"family":"Rye","category":"display","variants":["regular"]},
    {"family":"STIX Two Text","category":"serif","variants":["regular","500","700"]},
    {"family":"Sahitya","category":"serif","variants":["regular","700"]},
    {"family":"Sail","category":"display","variants":["regular"]},
    {"family":"Saira","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Saira Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Saira Extra Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Saira Semi Condensed","category":"sans-serif","variants":["regular","700"]},
    {"family":"Salsa","category":"display","variants":["regular"]},
    {"family":"Sanchez","category":"serif","variants":["regular","italic"]},
    {"family":"Sancreek","category":"display","variants":["regular"]},
    {"family":"Sansita","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Sansita Swashed","category":"display","variants":["300","regular","700"]},
    {"family":"Sarabun","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sawarabi Gothic","category":"sans-serif","variants":["regular"]},
    {"family":"Sawarabi Mincho","category":"serif","variants":["regular"]},
    {"family":"Scheherazade New","category":"serif","variants":["regular","700"]},
    {"family":"Scada","category":"sans-serif","variants":["regular","700","italic"]},
    {"family":"Secular One","category":"sans-serif","variants":["regular"]},
    {"family":"Sevillana","category":"display","variants":["regular"]},
    {"family":"Seymour One","category":"sans-serif","variants":["regular"]},
    {"family":"Share","category":"display","variants":["regular","700","italic"]},
    {"family":"Share Tech","category":"sans-serif","variants":["regular"]},
    {"family":"Shippori Antique","category":"sans-serif","variants":["regular"]},
    {"family":"Shippori Mincho","category":"serif","variants":["regular","500","700"]},
    {"family":"Shojumaru","category":"display","variants":["regular"]},
    {"family":"Short Stack","category":"handwriting","variants":["regular"]},
    {"family":"Shrikhand","category":"display","variants":["regular"]},
    {"family":"Siemreap","category":"display","variants":["regular"]},
    {"family":"Sigmar","category":"display","variants":["regular"]},
    {"family":"Signika","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Signika Negative","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Simonetta","category":"display","variants":["regular","italic"]},
    {"family":"Single Day","category":"display","variants":["regular"]},
    {"family":"Sintony","category":"sans-serif","variants":["regular","700"]},
    {"family":"Sirin Stencil","category":"display","variants":["regular"]},
    {"family":"Six Caps","category":"sans-serif","variants":["regular"]},
    {"family":"Skranji","category":"display","variants":["regular","700"]},
    {"family":"Slackey","category":"display","variants":["regular"]},
    {"family":"Smokum","category":"display","variants":["regular"]},
    {"family":"Smythe","category":"display","variants":["regular"]},
    {"family":"Sniglet","category":"display","variants":["regular","800"]},
    {"family":"Snippet","category":"sans-serif","variants":["regular"]},
    {"family":"Snowburst One","category":"display","variants":["regular"]},
    {"family":"Sofia","category":"handwriting","variants":["regular"]},
    {"family":"Sofia Sans","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Sonsie One","category":"display","variants":["regular"]},
    {"family":"Sora","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Sorts Mill Goudy","category":"serif","variants":["regular","italic"]},
    {"family":"Source Sans Pro","category":"sans-serif","variants":["regular","700"]},
    {"family":"Source Serif Pro","category":"serif","variants":["regular","700"]},
    {"family":"Space Grotesk","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Spartan","category":"sans-serif","variants":["regular","700"]},
    {"family":"Special Elite","category":"display","variants":["regular"]},
    {"family":"Spectral SC","category":"serif","variants":["regular","700"]},
    {"family":"Spicy Rice","category":"display","variants":["regular"]},
    {"family":"Spinnaker","category":"sans-serif","variants":["regular"]},
    {"family":"Spirax","category":"display","variants":["regular"]},
    {"family":"Square Peg","category":"handwriting","variants":["regular"]},
    {"family":"Sree Krushnadevaraya","category":"serif","variants":["regular"]},
    {"family":"Sriracha","category":"handwriting","variants":["regular"]},
    {"family":"Srisakdi","category":"handwriting","variants":["regular","700"]},
    {"family":"Staatliches","category":"display","variants":["regular"]},
    {"family":"Stardos Stencil","category":"display","variants":["regular","700"]},
    {"family":"Stick","category":"sans-serif","variants":["regular"]},
    {"family":"Stick No Bills","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Stint Ultra Condensed","category":"serif","variants":["regular"]},
    {"family":"Stint Ultra Expanded","category":"serif","variants":["regular"]},
    {"family":"Stoke","category":"serif","variants":["300","regular"]},
    {"family":"Strait","category":"sans-serif","variants":["regular"]},
    {"family":"Style Script","category":"handwriting","variants":["regular"]},
    {"family":"Stylish","category":"sans-serif","variants":["regular"]},
    {"family":"Sue Ellen Francisco","category":"handwriting","variants":["regular"]},
    {"family":"Sunshiney","category":"handwriting","variants":["regular"]},
    {"family":"Supermercado One","category":"display","variants":["regular"]},
    {"family":"Sura","category":"serif","variants":["regular","700"]},
    {"family":"Suranna","category":"serif","variants":["regular"]},
    {"family":"Suravaram","category":"serif","variants":["regular"]},
    {"family":"Suwannaphum","category":"display","variants":["regular"]},
    {"family":"Swanky and Moo Moo","category":"handwriting","variants":["regular"]},
    {"family":"Syncopate","category":"sans-serif","variants":["regular","700"]},
    {"family":"Syne","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Syne Mono","category":"monospace","variants":["regular"]},
    {"family":"Syne Tactile","category":"display","variants":["regular"]},
    {"family":"Tajawal","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Tangerine","category":"handwriting","variants":["regular","700"]},
    {"family":"Tapestry","category":"handwriting","variants":["regular"]},
    {"family":"Taprom","category":"display","variants":["regular"]},
    {"family":"Tauri","category":"sans-serif","variants":["regular"]},
    {"family":"Taviraj","category":"serif","variants":["regular","500","700"]},
    {"family":"Teko","category":"sans-serif","variants":["300","regular","500","700"]},
    {"family":"Tenali Ramakrishna","category":"sans-serif","variants":["regular"]},
    {"family":"Tenor Sans","category":"sans-serif","variants":["regular"]},
    {"family":"Text Me One","category":"sans-serif","variants":["regular"]},
    {"family":"Thasadith","category":"sans-serif","variants":["regular","700"]},
    {"family":"The Girl Next Door","category":"handwriting","variants":["regular"]},
    {"family":"The Nautigal","category":"handwriting","variants":["regular","700"]},
    {"family":"Tienne","category":"serif","variants":["regular","700"]},
    {"family":"Tillana","category":"display","variants":["regular","500","700"]},
    {"family":"Timmana","category":"sans-serif","variants":["regular"]},
    {"family":"Tinos","category":"serif","variants":["regular","700","italic"]},
    {"family":"Titan One","category":"display","variants":["regular"]},
    {"family":"Titillium Web","category":"sans-serif","variants":["regular","600","700"]},
    {"family":"Tomorrow","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Trade Winds","category":"display","variants":["regular"]},
    {"family":"Train One","category":"display","variants":["regular"]},
    {"family":"Trirong","category":"serif","variants":["regular","500","700"]},
    {"family":"Trispace","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Trocchi","category":"serif","variants":["regular"]},
    {"family":"Trochut","category":"display","variants":["regular","italic"]},
    {"family":"Trykker","category":"serif","variants":["regular"]},
    {"family":"Tuppence","category":"display","variants":["regular","700"]},
    {"family":"Turret Road","category":"display","variants":["regular","700"]},
    {"family":"Twinkle Star","category":"handwriting","variants":["regular"]},
    {"family":"Unkempt","category":"display","variants":["regular","700"]},
    {"family":"Urbanist","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Uroob","category":"sans-serif","variants":["regular"]},
    {"family":"Varta","category":"sans-serif","variants":["300","regular","500","700"]},
    {"family":"Vesper Libre","category":"serif","variants":["regular","700"]},
    {"family":"Viaoda Libre","category":"display","variants":["regular"]},
    {"family":"Vibes","category":"handwriting","variants":["regular"]},
    {"family":"Vibur","category":"handwriting","variants":["regular"]},
    {"family":"Vidaloka","category":"serif","variants":["regular"]},
    {"family":"Viga","category":"sans-serif","variants":["regular"]},
    {"family":"Voces","category":"sans-serif","variants":["regular"]},
    {"family":"Volkhov","category":"serif","variants":["regular","700","italic"]},
    {"family":"Vollkorn","category":"serif","variants":["regular","500","700"]},
    {"family":"Vollkorn SC","category":"serif","variants":["regular","700"]},
    {"family":"Voltaire","category":"sans-serif","variants":["regular"]},
    {"family":"Warnes","category":"display","variants":["regular"]},
    {"family":"Water Brush","category":"handwriting","variants":["regular"]},
    {"family":"Waterfall","category":"handwriting","variants":["regular"]},
    {"family":"Wavefont","category":"display","variants":["regular"]},
    {"family":"Wellfleet","category":"display","variants":["regular"]},
    {"family":"Wendy One","category":"sans-serif","variants":["regular"]},
    {"family":"Whisper","category":"handwriting","variants":["regular"]},
    {"family":"WindSong","category":"handwriting","variants":["regular"]},
    {"family":"Wire One","category":"sans-serif","variants":["regular"]},
    {"family":"Wix Madefor Display","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Wix Madefor Text","category":"sans-serif","variants":["regular","700"]},
    {"family":"Xanh Mono","category":"monospace","variants":["regular","italic"]},
    {"family":"Yaldevi","category":"sans-serif","variants":["regular","700"]},
    {"family":"Yanone Kaffeesatz","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Yantramanav","category":"sans-serif","variants":["regular","700"]},
    {"family":"Yarndings 12","category":"display","variants":["regular"]},
    {"family":"Yeseva One","category":"display","variants":["regular"]},
    {"family":"Yesteryear","category":"handwriting","variants":["regular"]},
    {"family":"Yomogi","category":"handwriting","variants":["regular"]},
    {"family":"Young Serif","category":"serif","variants":["regular"]},
    {"family":"Yrsa","category":"serif","variants":["regular","500","700"]},
    {"family":"Yuji Boku","category":"serif","variants":["regular"]},
    {"family":"Yuji Mai","category":"serif","variants":["regular"]},
    {"family":"Yuji Syuku","category":"serif","variants":["regular"]},
    {"family":"Yusei Magic","category":"sans-serif","variants":["regular"]},
    {"family":"ZCOOL KuaiLe","category":"display","variants":["regular"]},
    {"family":"ZCOOL QingKe HuangYou","category":"display","variants":["regular"]},
    {"family":"ZCOOL XiaoWei","category":"display","variants":["regular"]},
    {"family":"Zen Antique","category":"serif","variants":["regular"]},
    {"family":"Zen Antique Soft","category":"serif","variants":["regular"]},
    {"family":"Zen Dots","category":"display","variants":["regular"]},
    {"family":"Zen Kaku Gothic Antique","category":"sans-serif","variants":["regular","700"]},
    {"family":"Zen Kaku Gothic New","category":"sans-serif","variants":["regular","700"]},
    {"family":"Zen Kurenaido","category":"sans-serif","variants":["regular"]},
    {"family":"Zen Loop","category":"display","variants":["regular","italic"]},
    {"family":"Zen Maru Gothic","category":"sans-serif","variants":["regular","500","700"]},
    {"family":"Zen Old Mincho","category":"serif","variants":["regular","700"]},
    {"family":"Zen Tokyo Zoo","category":"display","variants":["regular"]},
    {"family":"Zeyada","category":"handwriting","variants":["regular"]},
    {"family":"Zilla Slab Highlight","category":"display","variants":["regular","700"]},
]

# Fontshare — SIL Open Font License
FONTSHARE_FONTS = [
    {"family":"Satoshi","category":"sans-serif","source":"fontshare","dl_id":"satoshi"},
    {"family":"Cabinet Grotesk","category":"sans-serif","source":"fontshare","dl_id":"cabinet-grotesk"},
    {"family":"Clash Display","category":"display","source":"fontshare","dl_id":"clash-display"},
    {"family":"Clash Grotesk","category":"sans-serif","source":"fontshare","dl_id":"clash-grotesk"},
    {"family":"General Sans","category":"sans-serif","source":"fontshare","dl_id":"general-sans"},
    {"family":"Switzer","category":"sans-serif","source":"fontshare","dl_id":"switzer"},
    {"family":"Boska","category":"serif","source":"fontshare","dl_id":"boska"},
    {"family":"Chillax","category":"display","source":"fontshare","dl_id":"chillax"},
    {"family":"Supreme","category":"sans-serif","source":"fontshare","dl_id":"supreme"},
    {"family":"Author","category":"sans-serif","source":"fontshare","dl_id":"author"},
    {"family":"Excon","category":"sans-serif","source":"fontshare","dl_id":"excon"},
    {"family":"Synonym","category":"sans-serif","source":"fontshare","dl_id":"synonym"},
    {"family":"Ranade","category":"sans-serif","source":"fontshare","dl_id":"ranade"},
    {"family":"Pencerio","category":"serif","source":"fontshare","dl_id":"pencerio"},
    {"family":"Gambetta","category":"serif","source":"fontshare","dl_id":"gambetta"},
    {"family":"Zodiak","category":"serif","source":"fontshare","dl_id":"zodiak"},
    {"family":"Alpino","category":"sans-serif","source":"fontshare","dl_id":"alpino"},
    {"family":"Tanker","category":"display","source":"fontshare","dl_id":"tanker"},
    {"family":"Sora","category":"sans-serif","source":"fontshare","dl_id":"sora"},
    {"family":"Pilcrow Rounded","category":"sans-serif","source":"fontshare","dl_id":"pilcrow-rounded"},
]

# League of Moveable Type — SIL Open Font License
LEAGUE_FONTS = [
    {"family":"League Spartan","category":"sans-serif","source":"league"},
    {"family":"League Gothic","category":"sans-serif","source":"league"},
    {"family":"League Mono","category":"monospace","source":"league"},
    {"family":"Chunk Five","category":"serif","source":"league"},
    {"family":"Sniglet","category":"display","source":"league"},
    {"family":"Orbitron","category":"display","source":"league"},
    {"family":"Junction","category":"sans-serif","source":"league"},
    {"family":"Ostrich Sans","category":"sans-serif","source":"league"},
    {"family":"Prociono","category":"serif","source":"league"},
    {"family":"TW Cen MT","category":"sans-serif","source":"league"},
]

def get_all_fonts():
    """Tüm fontları birleştir ve döndür"""
    result = []
    # Google Fonts
    for i, f in enumerate(GOOGLE_FONTS):
        result.append({
            'family': f['family'],
            'category': f['category'],
            'source': 'google',
            'variants': f.get('variants', ['regular']),
            'pop': i
        })
    # Fontshare
    for i, f in enumerate(FONTSHARE_FONTS):
        result.append({
            'family': f['family'],
            'category': f['category'],
            'source': 'fontshare',
            'dl_id': f.get('dl_id', f['family'].lower().replace(' ','-')),
            'pop': i - 50  # Fontshare fontları öne çıksın
        })
    # League
    for i, f in enumerate(LEAGUE_FONTS):
        result.append({
            'family': f['family'],
            'category': f['category'],
            'source': 'league',
            'pop': i + 100
        })
    return result

if __name__ == '__main__':
    fonts = get_all_fonts()
    print(f"Toplam font: {len(fonts)}")
    cats = {}
    for f in fonts:
        cats[f['category']] = cats.get(f['category'], 0) + 1
    print("Kategoriler:", cats)
